/*
 * generated by Xtext 2.25.0
 */
package org.example.domainmodel.ide.contentassist.antlr;

import com.google.common.collect.ImmutableMap;
import com.google.inject.Inject;
import com.google.inject.Singleton;
import java.util.Map;
import org.eclipse.xtext.AbstractElement;
import org.eclipse.xtext.ide.editor.contentassist.antlr.AbstractContentAssistParser;
import org.example.domainmodel.ide.contentassist.antlr.internal.InternalDomainmodelParser;
import org.example.domainmodel.services.DomainmodelGrammarAccess;

public class DomainmodelParser extends AbstractContentAssistParser {

	@Singleton
	public static final class NameMappings {
		
		private final Map<AbstractElement, String> mappings;
		
		@Inject
		public NameMappings(DomainmodelGrammarAccess grammarAccess) {
			ImmutableMap.Builder<AbstractElement, String> builder = ImmutableMap.builder();
			init(builder, grammarAccess);
			this.mappings = builder.build();
		}
		
		public String getRuleName(AbstractElement element) {
			return mappings.get(element);
		}
		
		private static void init(ImmutableMap.Builder<AbstractElement, String> builder, DomainmodelGrammarAccess grammarAccess) {
			builder.put(grammarAccess.getModelAccess().getAlternatives_9(), "rule__Model__Alternatives_9");
			builder.put(grammarAccess.getValueAccess().getValueAlternatives_0(), "rule__Value__ValueAlternatives_0");
			builder.put(grammarAccess.getDataTypeAccess().getAlternatives(), "rule__DataType__Alternatives");
			builder.put(grammarAccess.getModelAccess().getGroup(), "rule__Model__Group__0");
			builder.put(grammarAccess.getVariableAccess().getGroup(), "rule__Variable__Group__0");
			builder.put(grammarAccess.getVariableAccess().getGroup_4(), "rule__Variable__Group_4__0");
			builder.put(grammarAccess.getConstantAccess().getGroup(), "rule__Constant__Group__0");
			builder.put(grammarAccess.getCycleDefAccess().getGroup(), "rule__CycleDef__Group__0");
			builder.put(grammarAccess.getClockAccess().getGroup(), "rule__Clock__Group__0");
			builder.put(grammarAccess.getClockAccess().getGroup_2(), "rule__Clock__Group_2__0");
			builder.put(grammarAccess.getInterfaceAccess().getGroup(), "rule__Interface__Group__0");
			builder.put(grammarAccess.getEventDeclAccess().getGroup(), "rule__EventDecl__Group__0");
			builder.put(grammarAccess.getModelAccess().getInterfaceAssignment_1(), "rule__Model__InterfaceAssignment_1");
			builder.put(grammarAccess.getModelAccess().getEventsAssignment_3(), "rule__Model__EventsAssignment_3");
			builder.put(grammarAccess.getModelAccess().getNameAssignment_6(), "rule__Model__NameAssignment_6");
			builder.put(grammarAccess.getModelAccess().getCycleDefAssignment_8(), "rule__Model__CycleDefAssignment_8");
			builder.put(grammarAccess.getModelAccess().getConstantsAssignment_9_0(), "rule__Model__ConstantsAssignment_9_0");
			builder.put(grammarAccess.getModelAccess().getVariablesAssignment_9_1(), "rule__Model__VariablesAssignment_9_1");
			builder.put(grammarAccess.getModelAccess().getClockAssignment_9_2(), "rule__Model__ClockAssignment_9_2");
			builder.put(grammarAccess.getVariableAccess().getNameAssignment_1(), "rule__Variable__NameAssignment_1");
			builder.put(grammarAccess.getVariableAccess().getTypeAssignment_3(), "rule__Variable__TypeAssignment_3");
			builder.put(grammarAccess.getVariableAccess().getInitialValueAssignment_4_1(), "rule__Variable__InitialValueAssignment_4_1");
			builder.put(grammarAccess.getConstantAccess().getNameAssignment_1(), "rule__Constant__NameAssignment_1");
			builder.put(grammarAccess.getConstantAccess().getTypeAssignment_3(), "rule__Constant__TypeAssignment_3");
			builder.put(grammarAccess.getCycleDefAccess().getValueAssignment_3(), "rule__CycleDef__ValueAssignment_3");
			builder.put(grammarAccess.getClockAccess().getNameAssignment_1(), "rule__Clock__NameAssignment_1");
			builder.put(grammarAccess.getClockAccess().getInitialValueAssignment_2_1(), "rule__Clock__InitialValueAssignment_2_1");
			builder.put(grammarAccess.getInterfaceAccess().getNameAssignment_1(), "rule__Interface__NameAssignment_1");
			builder.put(grammarAccess.getInterfaceAccess().getEventsAssignment_3(), "rule__Interface__EventsAssignment_3");
			builder.put(grammarAccess.getEventDeclAccess().getNameAssignment_1(), "rule__EventDecl__NameAssignment_1");
			builder.put(grammarAccess.getValueAccess().getValueAssignment(), "rule__Value__ValueAssignment");
		}
	}
	
	@Inject
	private NameMappings nameMappings;

	@Inject
	private DomainmodelGrammarAccess grammarAccess;

	@Override
	protected InternalDomainmodelParser createParser() {
		InternalDomainmodelParser result = new InternalDomainmodelParser(null);
		result.setGrammarAccess(grammarAccess);
		return result;
	}

	@Override
	protected String getRuleName(AbstractElement element) {
		return nameMappings.getRuleName(element);
	}

	@Override
	protected String[] getInitialHiddenTokens() {
		return new String[] { "RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT" };
	}

	public DomainmodelGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(DomainmodelGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
	public NameMappings getNameMappings() {
		return nameMappings;
	}
	
	public void setNameMappings(NameMappings nameMappings) {
		this.nameMappings = nameMappings;
	}
}
