/*
 * generated by Xtext 2.25.0
 */
grammar InternalDomainmodel;

options {
	superClass=AbstractInternalAntlrParser;
}

@lexer::header {
package org.example.domainmodel.parser.antlr.internal;

// Hack: Use our own Lexer superclass by means of import. 
// Currently there is no other way to specify the superclass for the lexer.
import org.eclipse.xtext.parser.antlr.Lexer;
}

@parser::header {
package org.example.domainmodel.parser.antlr.internal;

import org.eclipse.xtext.*;
import org.eclipse.xtext.parser.*;
import org.eclipse.xtext.parser.impl.*;
import org.eclipse.emf.ecore.util.EcoreUtil;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.emf.common.util.Enumerator;
import org.eclipse.xtext.parser.antlr.AbstractInternalAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import org.eclipse.xtext.parser.antlr.XtextTokenStream.HiddenTokens;
import org.eclipse.xtext.parser.antlr.AntlrDatatypeRuleToken;
import org.example.domainmodel.services.DomainmodelGrammarAccess;

}

@parser::members {

 	private DomainmodelGrammarAccess grammarAccess;

    public InternalDomainmodelParser(TokenStream input, DomainmodelGrammarAccess grammarAccess) {
        this(input);
        this.grammarAccess = grammarAccess;
        registerRules(grammarAccess.getGrammar());
    }

    @Override
    protected String getFirstRuleName() {
    	return "Model";
   	}

   	@Override
   	protected DomainmodelGrammarAccess getGrammarAccess() {
   		return grammarAccess;
   	}

}

@rulecatch {
    catch (RecognitionException re) {
        recover(input,re);
        appendSkippedTokens();
    }
}

// Entry rule entryRuleModel
entryRuleModel returns [EObject current=null]:
	{ newCompositeNode(grammarAccess.getModelRule()); }
	iv_ruleModel=ruleModel
	{ $current=$iv_ruleModel.current; }
	EOF;

// Rule Model
ruleModel returns [EObject current=null]
@init {
	enterRule();
}
@after {
	leaveRule();
}:
	(
		(
			(
				{
					newCompositeNode(grammarAccess.getModelAccess().getInterfaceInterfaceParserRuleCall_0_0());
				}
				lv_interface_0_0=ruleInterface
				{
					if ($current==null) {
						$current = createModelElementForParent(grammarAccess.getModelRule());
					}
					add(
						$current,
						"interface",
						lv_interface_0_0,
						"org.example.domainmodel.Domainmodel.Interface");
					afterParserOrEnumRuleCall();
				}
			)
		)*
		otherlv_1='stm'
		{
			newLeafNode(otherlv_1, grammarAccess.getModelAccess().getStmKeyword_1());
		}
		(
			(
				lv_name_2_0=RULE_ID
				{
					newLeafNode(lv_name_2_0, grammarAccess.getModelAccess().getNameIDTerminalRuleCall_2_0());
				}
				{
					if ($current==null) {
						$current = createModelElement(grammarAccess.getModelRule());
					}
					setWithLastConsumed(
						$current,
						"name",
						lv_name_2_0,
						"org.eclipse.xtext.common.Terminals.ID");
				}
			)
		)
		otherlv_3='{'
		{
			newLeafNode(otherlv_3, grammarAccess.getModelAccess().getLeftCurlyBracketKeyword_3());
		}
		(
			(
				{
					newCompositeNode(grammarAccess.getModelAccess().getCycleDefCycleDefParserRuleCall_4_0());
				}
				lv_cycleDef_4_0=ruleCycleDef
				{
					if ($current==null) {
						$current = createModelElementForParent(grammarAccess.getModelRule());
					}
					set(
						$current,
						"cycleDef",
						lv_cycleDef_4_0,
						"org.example.domainmodel.Domainmodel.CycleDef");
					afterParserOrEnumRuleCall();
				}
			)
		)?
		(
			(
				{
					newCompositeNode(grammarAccess.getModelAccess().getConstantsConstantParserRuleCall_5_0());
				}
				lv_constants_5_0=ruleConstant
				{
					if ($current==null) {
						$current = createModelElementForParent(grammarAccess.getModelRule());
					}
					add(
						$current,
						"constants",
						lv_constants_5_0,
						"org.example.domainmodel.Domainmodel.Constant");
					afterParserOrEnumRuleCall();
				}
			)
		)*
		(
			(
				{
					newCompositeNode(grammarAccess.getModelAccess().getVariablesVariableParserRuleCall_6_0());
				}
				lv_variables_6_0=ruleVariable
				{
					if ($current==null) {
						$current = createModelElementForParent(grammarAccess.getModelRule());
					}
					add(
						$current,
						"variables",
						lv_variables_6_0,
						"org.example.domainmodel.Domainmodel.Variable");
					afterParserOrEnumRuleCall();
				}
			)
		)*
		(
			(
				{
					newCompositeNode(grammarAccess.getModelAccess().getClockClockParserRuleCall_7_0());
				}
				lv_clock_7_0=ruleClock
				{
					if ($current==null) {
						$current = createModelElementForParent(grammarAccess.getModelRule());
					}
					add(
						$current,
						"clock",
						lv_clock_7_0,
						"org.example.domainmodel.Domainmodel.Clock");
					afterParserOrEnumRuleCall();
				}
			)
		)*
		(
			(
				{
					newCompositeNode(grammarAccess.getModelAccess().getContextsContextDeclParserRuleCall_8_0());
				}
				lv_contexts_8_0=ruleContextDecl
				{
					if ($current==null) {
						$current = createModelElementForParent(grammarAccess.getModelRule());
					}
					add(
						$current,
						"contexts",
						lv_contexts_8_0,
						"org.example.domainmodel.Domainmodel.ContextDecl");
					afterParserOrEnumRuleCall();
				}
			)
		)*
		otherlv_9='}'
		{
			newLeafNode(otherlv_9, grammarAccess.getModelAccess().getRightCurlyBracketKeyword_9());
		}
	)
;

// Entry rule entryRuleInterface
entryRuleInterface returns [EObject current=null]:
	{ newCompositeNode(grammarAccess.getInterfaceRule()); }
	iv_ruleInterface=ruleInterface
	{ $current=$iv_ruleInterface.current; }
	EOF;

// Rule Interface
ruleInterface returns [EObject current=null]
@init {
	enterRule();
}
@after {
	leaveRule();
}:
	(
		otherlv_0='interface'
		{
			newLeafNode(otherlv_0, grammarAccess.getInterfaceAccess().getInterfaceKeyword_0());
		}
		(
			(
				lv_name_1_0=RULE_ID
				{
					newLeafNode(lv_name_1_0, grammarAccess.getInterfaceAccess().getNameIDTerminalRuleCall_1_0());
				}
				{
					if ($current==null) {
						$current = createModelElement(grammarAccess.getInterfaceRule());
					}
					setWithLastConsumed(
						$current,
						"name",
						lv_name_1_0,
						"org.eclipse.xtext.common.Terminals.ID");
				}
			)
		)
		otherlv_2='{'
		{
			newLeafNode(otherlv_2, grammarAccess.getInterfaceAccess().getLeftCurlyBracketKeyword_2());
		}
		(
			(
				(
					{
						newCompositeNode(grammarAccess.getInterfaceAccess().getOperationsOperationDeclParserRuleCall_3_0_0());
					}
					lv_operations_3_0=ruleOperationDecl
					{
						if ($current==null) {
							$current = createModelElementForParent(grammarAccess.getInterfaceRule());
						}
						add(
							$current,
							"operations",
							lv_operations_3_0,
							"org.example.domainmodel.Domainmodel.OperationDecl");
						afterParserOrEnumRuleCall();
					}
				)
			)
			    |
			(
				(
					{
						newCompositeNode(grammarAccess.getInterfaceAccess().getEventsEventDeclParserRuleCall_3_1_0());
					}
					lv_events_4_0=ruleEventDecl
					{
						if ($current==null) {
							$current = createModelElementForParent(grammarAccess.getInterfaceRule());
						}
						add(
							$current,
							"events",
							lv_events_4_0,
							"org.example.domainmodel.Domainmodel.EventDecl");
						afterParserOrEnumRuleCall();
					}
				)
			)
		)*
		otherlv_5='}'
		{
			newLeafNode(otherlv_5, grammarAccess.getInterfaceAccess().getRightCurlyBracketKeyword_4());
		}
	)
;

// Entry rule entryRuleOperationDecl
entryRuleOperationDecl returns [EObject current=null]:
	{ newCompositeNode(grammarAccess.getOperationDeclRule()); }
	iv_ruleOperationDecl=ruleOperationDecl
	{ $current=$iv_ruleOperationDecl.current; }
	EOF;

// Rule OperationDecl
ruleOperationDecl returns [EObject current=null]
@init {
	enterRule();
}
@after {
	leaveRule();
}:
	(
		(
			(
				lv_name_0_0=RULE_ID
				{
					newLeafNode(lv_name_0_0, grammarAccess.getOperationDeclAccess().getNameIDTerminalRuleCall_0_0());
				}
				{
					if ($current==null) {
						$current = createModelElement(grammarAccess.getOperationDeclRule());
					}
					setWithLastConsumed(
						$current,
						"name",
						lv_name_0_0,
						"org.eclipse.xtext.common.Terminals.ID");
				}
			)
		)
		otherlv_1='('
		{
			newLeafNode(otherlv_1, grammarAccess.getOperationDeclAccess().getLeftParenthesisKeyword_1());
		}
		(
			(
				(
					{
						newCompositeNode(grammarAccess.getOperationDeclAccess().getParamsParamParserRuleCall_2_0_0());
					}
					lv_params_2_0=ruleParam
					{
						if ($current==null) {
							$current = createModelElementForParent(grammarAccess.getOperationDeclRule());
						}
						add(
							$current,
							"params",
							lv_params_2_0,
							"org.example.domainmodel.Domainmodel.Param");
						afterParserOrEnumRuleCall();
					}
				)
			)
			(
				otherlv_3=','
				{
					newLeafNode(otherlv_3, grammarAccess.getOperationDeclAccess().getCommaKeyword_2_1_0());
				}
				(
					(
						{
							newCompositeNode(grammarAccess.getOperationDeclAccess().getParamsParamParserRuleCall_2_1_1_0());
						}
						lv_params_4_0=ruleParam
						{
							if ($current==null) {
								$current = createModelElementForParent(grammarAccess.getOperationDeclRule());
							}
							add(
								$current,
								"params",
								lv_params_4_0,
								"org.example.domainmodel.Domainmodel.Param");
							afterParserOrEnumRuleCall();
						}
					)
				)
			)*
		)?
		otherlv_5=')'
		{
			newLeafNode(otherlv_5, grammarAccess.getOperationDeclAccess().getRightParenthesisKeyword_3());
		}
	)
;

// Entry rule entryRuleEventDecl
entryRuleEventDecl returns [EObject current=null]:
	{ newCompositeNode(grammarAccess.getEventDeclRule()); }
	iv_ruleEventDecl=ruleEventDecl
	{ $current=$iv_ruleEventDecl.current; }
	EOF;

// Rule EventDecl
ruleEventDecl returns [EObject current=null]
@init {
	enterRule();
}
@after {
	leaveRule();
}:
	(
		otherlv_0='event'
		{
			newLeafNode(otherlv_0, grammarAccess.getEventDeclAccess().getEventKeyword_0());
		}
		(
			(
				lv_name_1_0=RULE_ID
				{
					newLeafNode(lv_name_1_0, grammarAccess.getEventDeclAccess().getNameIDTerminalRuleCall_1_0());
				}
				{
					if ($current==null) {
						$current = createModelElement(grammarAccess.getEventDeclRule());
					}
					setWithLastConsumed(
						$current,
						"name",
						lv_name_1_0,
						"org.eclipse.xtext.common.Terminals.ID");
				}
			)
		)
	)
;

// Entry rule entryRuleParam
entryRuleParam returns [EObject current=null]:
	{ newCompositeNode(grammarAccess.getParamRule()); }
	iv_ruleParam=ruleParam
	{ $current=$iv_ruleParam.current; }
	EOF;

// Rule Param
ruleParam returns [EObject current=null]
@init {
	enterRule();
}
@after {
	leaveRule();
}:
	(
		(
			(
				lv_name_0_0=RULE_ID
				{
					newLeafNode(lv_name_0_0, grammarAccess.getParamAccess().getNameIDTerminalRuleCall_0_0());
				}
				{
					if ($current==null) {
						$current = createModelElement(grammarAccess.getParamRule());
					}
					setWithLastConsumed(
						$current,
						"name",
						lv_name_0_0,
						"org.eclipse.xtext.common.Terminals.ID");
				}
			)
		)
		otherlv_1=':'
		{
			newLeafNode(otherlv_1, grammarAccess.getParamAccess().getColonKeyword_1());
		}
		(
			(
				{
					newCompositeNode(grammarAccess.getParamAccess().getTypeDataTypeEnumRuleCall_2_0());
				}
				lv_type_2_0=ruleDataType
				{
					if ($current==null) {
						$current = createModelElementForParent(grammarAccess.getParamRule());
					}
					set(
						$current,
						"type",
						lv_type_2_0,
						"org.example.domainmodel.Domainmodel.DataType");
					afterParserOrEnumRuleCall();
				}
			)
		)
	)
;

// Entry rule entryRuleContextDecl
entryRuleContextDecl returns [EObject current=null]:
	{ newCompositeNode(grammarAccess.getContextDeclRule()); }
	iv_ruleContextDecl=ruleContextDecl
	{ $current=$iv_ruleContextDecl.current; }
	EOF;

// Rule ContextDecl
ruleContextDecl returns [EObject current=null]
@init {
	enterRule();
}
@after {
	leaveRule();
}:
	(
		(
			(
				(
					lv_kind_0_1='input'
					{
						newLeafNode(lv_kind_0_1, grammarAccess.getContextDeclAccess().getKindInputKeyword_0_0_0());
					}
					{
						if ($current==null) {
							$current = createModelElement(grammarAccess.getContextDeclRule());
						}
						setWithLastConsumed($current, "kind", lv_kind_0_1, null);
					}
					    |
					lv_kind_0_2='output'
					{
						newLeafNode(lv_kind_0_2, grammarAccess.getContextDeclAccess().getKindOutputKeyword_0_0_1());
					}
					{
						if ($current==null) {
							$current = createModelElement(grammarAccess.getContextDeclRule());
						}
						setWithLastConsumed($current, "kind", lv_kind_0_2, null);
					}
				)
			)
		)
		otherlv_1='context'
		{
			newLeafNode(otherlv_1, grammarAccess.getContextDeclAccess().getContextKeyword_1());
		}
		otherlv_2='{'
		{
			newLeafNode(otherlv_2, grammarAccess.getContextDeclAccess().getLeftCurlyBracketKeyword_2());
		}
		otherlv_3='uses'
		{
			newLeafNode(otherlv_3, grammarAccess.getContextDeclAccess().getUsesKeyword_3());
		}
		(
			(
				{
					if ($current==null) {
						$current = createModelElement(grammarAccess.getContextDeclRule());
					}
				}
				otherlv_4=RULE_ID
				{
					newLeafNode(otherlv_4, grammarAccess.getContextDeclAccess().getUsedInterfacesInterfaceCrossReference_4_0());
				}
			)
		)
		(
			otherlv_5=','
			{
				newLeafNode(otherlv_5, grammarAccess.getContextDeclAccess().getCommaKeyword_5_0());
			}
			(
				(
					{
						if ($current==null) {
							$current = createModelElement(grammarAccess.getContextDeclRule());
						}
					}
					otherlv_6=RULE_ID
					{
						newLeafNode(otherlv_6, grammarAccess.getContextDeclAccess().getUsedInterfacesInterfaceCrossReference_5_1_0());
					}
				)
			)
		)*
		(
			(
				(
					{
						newCompositeNode(grammarAccess.getContextDeclAccess().getOpsOperationDeclParserRuleCall_6_0_0());
					}
					lv_ops_7_0=ruleOperationDecl
					{
						if ($current==null) {
							$current = createModelElementForParent(grammarAccess.getContextDeclRule());
						}
						add(
							$current,
							"ops",
							lv_ops_7_0,
							"org.example.domainmodel.Domainmodel.OperationDecl");
						afterParserOrEnumRuleCall();
					}
				)
			)
			    |
			(
				(
					{
						newCompositeNode(grammarAccess.getContextDeclAccess().getEventsEventDeclParserRuleCall_6_1_0());
					}
					lv_events_8_0=ruleEventDecl
					{
						if ($current==null) {
							$current = createModelElementForParent(grammarAccess.getContextDeclRule());
						}
						add(
							$current,
							"events",
							lv_events_8_0,
							"org.example.domainmodel.Domainmodel.EventDecl");
						afterParserOrEnumRuleCall();
					}
				)
			)
		)*
		otherlv_9='}'
		{
			newLeafNode(otherlv_9, grammarAccess.getContextDeclAccess().getRightCurlyBracketKeyword_7());
		}
	)
;

// Entry rule entryRuleConstant
entryRuleConstant returns [EObject current=null]:
	{ newCompositeNode(grammarAccess.getConstantRule()); }
	iv_ruleConstant=ruleConstant
	{ $current=$iv_ruleConstant.current; }
	EOF;

// Rule Constant
ruleConstant returns [EObject current=null]
@init {
	enterRule();
}
@after {
	leaveRule();
}:
	(
		otherlv_0='const'
		{
			newLeafNode(otherlv_0, grammarAccess.getConstantAccess().getConstKeyword_0());
		}
		(
			(
				lv_name_1_0=RULE_ID
				{
					newLeafNode(lv_name_1_0, grammarAccess.getConstantAccess().getNameIDTerminalRuleCall_1_0());
				}
				{
					if ($current==null) {
						$current = createModelElement(grammarAccess.getConstantRule());
					}
					setWithLastConsumed(
						$current,
						"name",
						lv_name_1_0,
						"org.eclipse.xtext.common.Terminals.ID");
				}
			)
		)
		otherlv_2=':'
		{
			newLeafNode(otherlv_2, grammarAccess.getConstantAccess().getColonKeyword_2());
		}
		(
			(
				{
					newCompositeNode(grammarAccess.getConstantAccess().getTypeDataTypeEnumRuleCall_3_0());
				}
				lv_type_3_0=ruleDataType
				{
					if ($current==null) {
						$current = createModelElementForParent(grammarAccess.getConstantRule());
					}
					set(
						$current,
						"type",
						lv_type_3_0,
						"org.example.domainmodel.Domainmodel.DataType");
					afterParserOrEnumRuleCall();
				}
			)
		)
	)
;

// Entry rule entryRuleVariable
entryRuleVariable returns [EObject current=null]:
	{ newCompositeNode(grammarAccess.getVariableRule()); }
	iv_ruleVariable=ruleVariable
	{ $current=$iv_ruleVariable.current; }
	EOF;

// Rule Variable
ruleVariable returns [EObject current=null]
@init {
	enterRule();
}
@after {
	leaveRule();
}:
	(
		otherlv_0='var'
		{
			newLeafNode(otherlv_0, grammarAccess.getVariableAccess().getVarKeyword_0());
		}
		(
			(
				lv_name_1_0=RULE_ID
				{
					newLeafNode(lv_name_1_0, grammarAccess.getVariableAccess().getNameIDTerminalRuleCall_1_0());
				}
				{
					if ($current==null) {
						$current = createModelElement(grammarAccess.getVariableRule());
					}
					setWithLastConsumed(
						$current,
						"name",
						lv_name_1_0,
						"org.eclipse.xtext.common.Terminals.ID");
				}
			)
		)
		otherlv_2=':'
		{
			newLeafNode(otherlv_2, grammarAccess.getVariableAccess().getColonKeyword_2());
		}
		(
			(
				{
					newCompositeNode(grammarAccess.getVariableAccess().getTypeDataTypeEnumRuleCall_3_0());
				}
				lv_type_3_0=ruleDataType
				{
					if ($current==null) {
						$current = createModelElementForParent(grammarAccess.getVariableRule());
					}
					set(
						$current,
						"type",
						lv_type_3_0,
						"org.example.domainmodel.Domainmodel.DataType");
					afterParserOrEnumRuleCall();
				}
			)
		)
		(
			otherlv_4='='
			{
				newLeafNode(otherlv_4, grammarAccess.getVariableAccess().getEqualsSignKeyword_4_0());
			}
			(
				(
					lv_initialValue_5_0=RULE_INT
					{
						newLeafNode(lv_initialValue_5_0, grammarAccess.getVariableAccess().getInitialValueINTTerminalRuleCall_4_1_0());
					}
					{
						if ($current==null) {
							$current = createModelElement(grammarAccess.getVariableRule());
						}
						setWithLastConsumed(
							$current,
							"initialValue",
							lv_initialValue_5_0,
							"org.eclipse.xtext.common.Terminals.INT");
					}
				)
			)
		)?
	)
;

// Entry rule entryRuleClock
entryRuleClock returns [EObject current=null]:
	{ newCompositeNode(grammarAccess.getClockRule()); }
	iv_ruleClock=ruleClock
	{ $current=$iv_ruleClock.current; }
	EOF;

// Rule Clock
ruleClock returns [EObject current=null]
@init {
	enterRule();
}
@after {
	leaveRule();
}:
	(
		otherlv_0='clock'
		{
			newLeafNode(otherlv_0, grammarAccess.getClockAccess().getClockKeyword_0());
		}
		(
			(
				lv_name_1_0=RULE_ID
				{
					newLeafNode(lv_name_1_0, grammarAccess.getClockAccess().getNameIDTerminalRuleCall_1_0());
				}
				{
					if ($current==null) {
						$current = createModelElement(grammarAccess.getClockRule());
					}
					setWithLastConsumed(
						$current,
						"name",
						lv_name_1_0,
						"org.eclipse.xtext.common.Terminals.ID");
				}
			)
		)
		(
			otherlv_2='='
			{
				newLeafNode(otherlv_2, grammarAccess.getClockAccess().getEqualsSignKeyword_2_0());
			}
			(
				(
					lv_initialValue_3_0=RULE_INT
					{
						newLeafNode(lv_initialValue_3_0, grammarAccess.getClockAccess().getInitialValueINTTerminalRuleCall_2_1_0());
					}
					{
						if ($current==null) {
							$current = createModelElement(grammarAccess.getClockRule());
						}
						setWithLastConsumed(
							$current,
							"initialValue",
							lv_initialValue_3_0,
							"org.eclipse.xtext.common.Terminals.INT");
					}
				)
			)
		)?
	)
;

// Entry rule entryRuleCycleDef
entryRuleCycleDef returns [EObject current=null]:
	{ newCompositeNode(grammarAccess.getCycleDefRule()); }
	iv_ruleCycleDef=ruleCycleDef
	{ $current=$iv_ruleCycleDef.current; }
	EOF;

// Rule CycleDef
ruleCycleDef returns [EObject current=null]
@init {
	enterRule();
}
@after {
	leaveRule();
}:
	(
		otherlv_0='cycleDef'
		{
			newLeafNode(otherlv_0, grammarAccess.getCycleDefAccess().getCycleDefKeyword_0());
		}
		otherlv_1='cycle'
		{
			newLeafNode(otherlv_1, grammarAccess.getCycleDefAccess().getCycleKeyword_1());
		}
		otherlv_2='=='
		{
			newLeafNode(otherlv_2, grammarAccess.getCycleDefAccess().getEqualsSignEqualsSignKeyword_2());
		}
		(
			(
				lv_value_3_0=RULE_INT
				{
					newLeafNode(lv_value_3_0, grammarAccess.getCycleDefAccess().getValueINTTerminalRuleCall_3_0());
				}
				{
					if ($current==null) {
						$current = createModelElement(grammarAccess.getCycleDefRule());
					}
					setWithLastConsumed(
						$current,
						"value",
						lv_value_3_0,
						"org.eclipse.xtext.common.Terminals.INT");
				}
			)
		)
	)
;

// Rule DataType
ruleDataType returns [Enumerator current=null]
@init {
	enterRule();
}
@after {
	leaveRule();
}:
	(
		(
			enumLiteral_0='NAT'
			{
				$current = grammarAccess.getDataTypeAccess().getNATEnumLiteralDeclaration_0().getEnumLiteral().getInstance();
				newLeafNode(enumLiteral_0, grammarAccess.getDataTypeAccess().getNATEnumLiteralDeclaration_0());
			}
		)
		    |
		(
			enumLiteral_1='INT'
			{
				$current = grammarAccess.getDataTypeAccess().getINTEnumLiteralDeclaration_1().getEnumLiteral().getInstance();
				newLeafNode(enumLiteral_1, grammarAccess.getDataTypeAccess().getINTEnumLiteralDeclaration_1());
			}
		)
		    |
		(
			enumLiteral_2='REAL'
			{
				$current = grammarAccess.getDataTypeAccess().getREALEnumLiteralDeclaration_2().getEnumLiteral().getInstance();
				newLeafNode(enumLiteral_2, grammarAccess.getDataTypeAccess().getREALEnumLiteralDeclaration_2());
			}
		)
		    |
		(
			enumLiteral_3='BOOL'
			{
				$current = grammarAccess.getDataTypeAccess().getBOOLEnumLiteralDeclaration_3().getEnumLiteral().getInstance();
				newLeafNode(enumLiteral_3, grammarAccess.getDataTypeAccess().getBOOLEnumLiteralDeclaration_3());
			}
		)
	)
;

RULE_ID : '^'? ('a'..'z'|'A'..'Z'|'_') ('a'..'z'|'A'..'Z'|'_'|'0'..'9')*;

RULE_INT : ('0'..'9')+;

RULE_STRING : ('"' ('\\' .|~(('\\'|'"')))* '"'|'\'' ('\\' .|~(('\\'|'\'')))* '\'');

RULE_ML_COMMENT : '/*' ( options {greedy=false;} : . )*'*/';

RULE_SL_COMMENT : '//' ~(('\n'|'\r'))* ('\r'? '\n')?;

RULE_WS : (' '|'\t'|'\r'|'\n')+;

RULE_ANY_OTHER : .;
