/**
 * generated by Xtext 2.25.0
 */
package org.example.domainmodel.generator;

import org.eclipse.emf.ecore.EObject;
import org.eclipse.emf.ecore.resource.Resource;
import org.eclipse.xtext.generator.AbstractGenerator;
import org.eclipse.xtext.generator.IFileSystemAccess2;
import org.eclipse.xtext.generator.IGeneratorContext;
import org.eclipse.xtext.xbase.lib.IteratorExtensions;
import org.example.domainmodel.domainmodel.Model;

/**
 * Generates code from your model files on save.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#code-generation
 */
@SuppressWarnings("all")
public class DomainmodelGenerator extends AbstractGenerator {
  @Override
  public void doGenerate(final Resource resource, final IFileSystemAccess2 fsa, final IGeneratorContext context) {
    EObject _head = IteratorExtensions.<EObject>head(resource.getAllContents());
    final Model UserLogic = ((Model) _head);
    if ((UserLogic != null)) {
      String _lastSegment = resource.getURI().lastSegment();
      String _plus = ("generated/" + _lastSegment);
      String path = (_plus + "/");
      fsa.generateFile((path + "logic_i.imp"), TextGenerator.generateBMachine(UserLogic));
    }
    EObject _head_1 = IteratorExtensions.<EObject>head(resource.getAllContents());
    final Model UserCtx = ((Model) _head_1);
    if ((UserCtx != null)) {
      String _lastSegment_1 = resource.getURI().lastSegment();
      String _plus_1 = ("generated/" + _lastSegment_1);
      String path_1 = (_plus_1 + "/");
      fsa.generateFile((path_1 + "user_ctx.mch"), UserCtxGenerator.generateUserCtx(UserCtx));
    }
  }
}
