package org.example.domainmodel.generator;

import org.eclipse.emf.common.util.EList;
import org.eclipse.xtend2.lib.StringConcatenation;
import org.example.domainmodel.domainmodel.Clock;
import org.example.domainmodel.domainmodel.DataType;
import org.example.domainmodel.domainmodel.Model;
import org.example.domainmodel.domainmodel.Variable;

@SuppressWarnings("all")
public class TextGenerator {
  public static CharSequence generateBMachine(final Model model) {
    StringConcatenation _builder = new StringConcatenation();
    _builder.append("IMPLEMENTATION");
    _builder.append("\n");
    _builder.newLineIfNotEmpty();
    _builder.append("logic_i");
    _builder.append("\n");
    _builder.newLineIfNotEmpty();
    _builder.append("\n");
    _builder.newLineIfNotEmpty();
    _builder.append("REFINES");
    _builder.append("\n");
    _builder.newLineIfNotEmpty();
    _builder.append("logic");
    _builder.append("\n");
    _builder.newLineIfNotEmpty();
    _builder.append("\n");
    _builder.newLineIfNotEmpty();
    _builder.append("SEES");
    _builder.append("\n");
    _builder.newLineIfNotEmpty();
    _builder.append("g_types,");
    _builder.append("\n");
    _builder.newLineIfNotEmpty();
    _builder.append("g_operators,");
    _builder.append("\n");
    _builder.newLineIfNotEmpty();
    _builder.append("io_constants,");
    _builder.append("\n");
    _builder.newLineIfNotEmpty();
    _builder.append("lchip_interface,");
    _builder.append("\n");
    _builder.newLineIfNotEmpty();
    _builder.append("user_ctx,");
    _builder.append("\n");
    _builder.newLineIfNotEmpty();
    _builder.append("inputs");
    _builder.append("\n");
    _builder.newLineIfNotEmpty();
    _builder.append("\n");
    _builder.append(" \t\t");
    _builder.newLineIfNotEmpty();
    _builder.append("CONCRETE_VARIABLES");
    _builder.append("\n");
    _builder.newLineIfNotEmpty();
    _builder.append("board_0_O1,");
    _builder.append("\n");
    _builder.newLineIfNotEmpty();
    _builder.append("board_0_O2,");
    _builder.append("\n");
    _builder.newLineIfNotEmpty();
    _builder.append("first_time,");
    _builder.append("\n");
    _builder.newLineIfNotEmpty();
    _builder.append("SM_");
    String _name = model.getName();
    _builder.append(_name);
    _builder.append("_state");
    _builder.append(", \n");
    _builder.newLineIfNotEmpty();
    _builder.append("cycle_timer,");
    _builder.append("\n");
    _builder.newLineIfNotEmpty();
    _builder.append("cycle_state,");
    _builder.append("\n");
    _builder.newLineIfNotEmpty();
    _builder.newLine();
    {
      EList<Clock> _clock = model.getClock();
      boolean _hasElements = false;
      for(final Clock c : _clock) {
        if (!_hasElements) {
          _hasElements = true;
        } else {
          _builder.appendImmediate(", ", "");
        }
        _builder.append("clock_");
        String _name_1 = c.getName();
        _builder.append(_name_1);
        _builder.append("_");
        _builder.append("\n");
        _builder.newLineIfNotEmpty();
      }
    }
    _builder.append("\n");
    _builder.newLineIfNotEmpty();
    {
      EList<Variable> _variables = model.getVariables();
      boolean _hasElements_1 = false;
      for(final Variable p : _variables) {
        if (!_hasElements_1) {
          _hasElements_1 = true;
        } else {
          _builder.appendImmediate(", ", "");
        }
        _builder.append("var_");
        String _name_2 = p.getName();
        _builder.append(_name_2);
        _builder.append("_");
        _builder.append("\n");
        _builder.newLineIfNotEmpty();
      }
    }
    _builder.append("\n");
    _builder.newLineIfNotEmpty();
    _builder.append("INVARIANT ");
    _builder.append("\n");
    _builder.newLineIfNotEmpty();
    _builder.append("board_0_O1 : uint8_t");
    _builder.append(" & \n");
    _builder.newLineIfNotEmpty();
    _builder.append("board_0_O2 : uint8_t");
    _builder.append(" & \n");
    _builder.newLineIfNotEmpty();
    _builder.append("first_time: BOOL");
    _builder.append(" & \n");
    _builder.newLineIfNotEmpty();
    _builder.append("SM_");
    String _name_3 = model.getName();
    _builder.append(_name_3);
    _builder.append("_state: uint32_t");
    _builder.append(" & \n");
    _builder.newLineIfNotEmpty();
    _builder.append("cycle_timer: uint32_t");
    _builder.append(" & \n");
    _builder.newLineIfNotEmpty();
    _builder.append("cycle_state: uint32_t");
    _builder.append(" & \n");
    _builder.newLineIfNotEmpty();
    _builder.newLine();
    {
      EList<Clock> _clock_1 = model.getClock();
      boolean _hasElements_2 = false;
      for(final Clock c_1 : _clock_1) {
        if (!_hasElements_2) {
          _hasElements_2 = true;
        } else {
          _builder.appendImmediate(" & ", "");
        }
        _builder.append("clock_");
        String _name_4 = c_1.getName();
        _builder.append(_name_4);
        _builder.append("_");
        _builder.append(" : uint32_t ");
        _builder.newLineIfNotEmpty();
      }
    }
    _builder.append("\n");
    _builder.newLineIfNotEmpty();
    {
      EList<Variable> _variables_1 = model.getVariables();
      boolean _hasElements_3 = false;
      for(final Variable p_1 : _variables_1) {
        if (!_hasElements_3) {
          _hasElements_3 = true;
        } else {
          _builder.appendImmediate(" & ", "");
        }
        _builder.append("var_");
        String _name_5 = p_1.getName();
        _builder.append(_name_5);
        _builder.append("_");
        _builder.append(" : ");
        String _mapType = TextGenerator.mapType(p_1.getType().toString());
        _builder.append(_mapType);
        _builder.append("\n");
        _builder.newLineIfNotEmpty();
      }
    }
    _builder.append("\n");
    _builder.append(" ");
    _builder.newLineIfNotEmpty();
    _builder.append("INITIALISATION");
    _builder.append("\n");
    _builder.newLineIfNotEmpty();
    _builder.append("\n");
    _builder.newLineIfNotEmpty();
    _builder.append("board_0_O1 := IO_OFF;");
    _builder.append("\n");
    _builder.newLineIfNotEmpty();
    _builder.append("board_0_O2 := IO_OFF;");
    _builder.append("\n");
    _builder.newLineIfNotEmpty();
    _builder.append("first_time := TRUE;");
    _builder.append("\n");
    _builder.newLineIfNotEmpty();
    _builder.append("SM_");
    String _name_6 = model.getName();
    _builder.append(_name_6);
    _builder.append("_state := 1;");
    _builder.append("\n");
    _builder.newLineIfNotEmpty();
    _builder.append("cycle_timer := 0;");
    _builder.append("\n");
    _builder.newLineIfNotEmpty();
    _builder.append("cycle_state := 1;");
    _builder.append("\n");
    _builder.newLineIfNotEmpty();
    {
      EList<Clock> _clock_2 = model.getClock();
      boolean _hasElements_4 = false;
      for(final Clock c_2 : _clock_2) {
        if (!_hasElements_4) {
          _hasElements_4 = true;
        } else {
          _builder.appendImmediate(" & ", "");
        }
        _builder.append("clock_");
        String _name_7 = c_2.getName();
        _builder.append(_name_7);
        _builder.append("_");
        _builder.append(" := 0");
        _builder.newLineIfNotEmpty();
      }
    }
    _builder.append("\n");
    _builder.newLineIfNotEmpty();
    {
      EList<Variable> _variables_2 = model.getVariables();
      boolean _hasElements_5 = false;
      for(final Variable v : _variables_2) {
        if (!_hasElements_5) {
          _hasElements_5 = true;
        } else {
          _builder.appendImmediate("; ", "");
        }
        _builder.append("var_");
        String _name_8 = v.getName();
        _builder.append(_name_8);
        _builder.append("_");
        _builder.append(":=");
        String _initValue = TextGenerator.initValue(v);
        _builder.append(_initValue);
        _builder.append(" ");
        _builder.append("\n");
        _builder.newLineIfNotEmpty();
      }
    }
    _builder.append("\n");
    _builder.newLineIfNotEmpty();
    _builder.append("LOCAL_OPERATIONS");
    _builder.append("\n");
    _builder.newLineIfNotEmpty();
    _builder.append("execute_model_cycle =");
    _builder.append("\n");
    _builder.newLineIfNotEmpty();
    _builder.append("PRE cycle_state = 4");
    _builder.append("\n");
    _builder.newLineIfNotEmpty();
    _builder.append("THEN");
    _builder.append("\n");
    _builder.newLineIfNotEmpty();
    _builder.append("SM_");
    String _name_9 = model.getName();
    _builder.append(_name_9);
    _builder.append("_state:: uint32_t ||");
    _builder.append("\n");
    _builder.newLineIfNotEmpty();
    _builder.append("first_time:: BOOL ||");
    _builder.append("\n");
    _builder.newLineIfNotEmpty();
    _builder.append("cycle_timer::uint32_t ||");
    _builder.append("\n");
    _builder.newLineIfNotEmpty();
    _builder.append("cycle_state ::uint32_t ||");
    _builder.append("\n");
    _builder.newLineIfNotEmpty();
    {
      EList<Variable> _variables_3 = model.getVariables();
      boolean _hasElements_6 = false;
      for(final Variable p_2 : _variables_3) {
        if (!_hasElements_6) {
          _hasElements_6 = true;
        } else {
          _builder.appendImmediate(" || ", "");
        }
        _builder.append("var_");
        String _name_10 = p_2.getName();
        _builder.append(_name_10);
        _builder.append("_");
        _builder.append(" :: ");
        String _mapType_1 = TextGenerator.mapType(p_2.getType().toString());
        _builder.append(_mapType_1);
        _builder.append("\n");
        _builder.newLineIfNotEmpty();
      }
    }
    _builder.append("\n");
    _builder.newLineIfNotEmpty();
    _builder.append("END; \t\t");
    _builder.newLine();
    _builder.append("\n");
    _builder.newLineIfNotEmpty();
    _builder.append("elapsed <-- since(timer) =");
    _builder.append("\n");
    _builder.newLineIfNotEmpty();
    _builder.append("PRE timer:uint32_t & elapsed:uint32_t");
    _builder.append("\n");
    _builder.newLineIfNotEmpty();
    _builder.append("THEN");
    _builder.append("\n");
    _builder.newLineIfNotEmpty();
    _builder.append("   ");
    _builder.append("elapsed::uint32_t");
    _builder.append("\n", "   ");
    _builder.newLineIfNotEmpty();
    _builder.append("END;");
    _builder.append("\n");
    _builder.newLineIfNotEmpty();
    _builder.append("\n");
    _builder.newLineIfNotEmpty();
    _builder.append("result <-- land(pp,qq) =");
    _builder.append("\n");
    _builder.newLineIfNotEmpty();
    _builder.append("PRE pp:BOOL & qq:BOOL & result:BOOL");
    _builder.append("\n");
    _builder.newLineIfNotEmpty();
    _builder.append("THEN");
    _builder.append("\n");
    _builder.newLineIfNotEmpty();
    _builder.append("   ");
    _builder.append("result::BOOL");
    _builder.append("\n", "   ");
    _builder.newLineIfNotEmpty();
    _builder.append("END;");
    _builder.append("\n");
    _builder.newLineIfNotEmpty();
    _builder.append("\n");
    _builder.newLineIfNotEmpty();
    _builder.append("result <-- lor(pp,qq) =");
    _builder.append("\n");
    _builder.append(" ");
    _builder.newLineIfNotEmpty();
    _builder.append("PRE pp:BOOL & qq:BOOL & result:BOOL");
    _builder.append("\n");
    _builder.newLineIfNotEmpty();
    _builder.append("THEN");
    _builder.append("\n");
    _builder.newLineIfNotEmpty();
    _builder.append("    ");
    _builder.append("result::BOOL");
    _builder.append("\n", "    ");
    _builder.newLineIfNotEmpty();
    _builder.append("END;");
    _builder.append("\n");
    _builder.newLineIfNotEmpty();
    _builder.append("\n");
    _builder.newLineIfNotEmpty();
    _builder.append("result <-- lnot(pp) =");
    _builder.append("\n");
    _builder.append(" ");
    _builder.newLineIfNotEmpty();
    _builder.append("PRE pp:BOOL & result:BOOL");
    _builder.append("\n");
    _builder.newLineIfNotEmpty();
    _builder.append("THEN");
    _builder.append("\n");
    _builder.newLineIfNotEmpty();
    _builder.append("    ");
    _builder.append("result::BOOL");
    _builder.append("\n", "    ");
    _builder.newLineIfNotEmpty();
    _builder.append("END;");
    _builder.append("\n");
    _builder.newLineIfNotEmpty();
    _builder.append("\n");
    _builder.newLineIfNotEmpty();
    _builder.append("reset_outputs =");
    _builder.append("\n");
    _builder.newLineIfNotEmpty();
    _builder.append("BEGIN");
    _builder.append("\n");
    _builder.newLineIfNotEmpty();
    _builder.append("    ");
    _builder.append("board_0_O1 :: uint8_t ||");
    _builder.append("\n", "    ");
    _builder.newLineIfNotEmpty();
    _builder.append("    ");
    _builder.append("board_0_O2 :: uint8_t");
    _builder.append("\n", "    ");
    _builder.newLineIfNotEmpty();
    _builder.append("END;");
    _builder.append("\n");
    _builder.newLineIfNotEmpty();
    _builder.append("\n");
    _builder.newLineIfNotEmpty();
    _builder.append("read_model_inputs =");
    _builder.append("\n");
    _builder.newLineIfNotEmpty();
    _builder.append("PRE cycle_state = 1");
    _builder.append("\n");
    _builder.newLineIfNotEmpty();
    _builder.append("THEN");
    _builder.append("\n");
    _builder.newLineIfNotEmpty();
    _builder.append("    ");
    _builder.append("cycle_state  :: uint8_t");
    _builder.append("\n", "    ");
    _builder.newLineIfNotEmpty();
    _builder.append("END;");
    _builder.append("\n");
    _builder.newLineIfNotEmpty();
    _builder.append("\n");
    _builder.newLineIfNotEmpty();
    _builder.append("write_model_outputs =");
    _builder.append("\n");
    _builder.newLineIfNotEmpty();
    _builder.append("PRE cycle_state = 3");
    _builder.append("\n");
    _builder.newLineIfNotEmpty();
    _builder.append("THEN");
    _builder.append("\n");
    _builder.newLineIfNotEmpty();
    _builder.append("    ");
    _builder.append("board_0_O1      :: uint8_t ||");
    _builder.append("\n", "    ");
    _builder.newLineIfNotEmpty();
    _builder.append("    ");
    _builder.append("board_0_O2      :: uint8_t ||");
    _builder.append("\n", "    ");
    _builder.newLineIfNotEmpty();
    _builder.append("    ");
    _builder.append("cycle_state     :: uint8_t");
    _builder.append("\n", "    ");
    _builder.newLineIfNotEmpty();
    _builder.append("END;");
    _builder.append("\n");
    _builder.newLineIfNotEmpty();
    _builder.append("\n");
    _builder.newLineIfNotEmpty();
    _builder.append("tock =");
    _builder.append("\n");
    _builder.newLineIfNotEmpty();
    _builder.append("BEGIN");
    _builder.append("\n");
    _builder.newLineIfNotEmpty();
    _builder.append("   ");
    _builder.append("skip");
    _builder.append("\n", "   ");
    _builder.newLineIfNotEmpty();
    _builder.append("END");
    _builder.append("\n");
    _builder.newLineIfNotEmpty();
    _builder.append("\n");
    _builder.newLineIfNotEmpty();
    _builder.append("OPERATIONS");
    _builder.append("\n");
    _builder.newLineIfNotEmpty();
    _builder.append("user_logic =");
    _builder.append("\n");
    _builder.append(" ");
    _builder.newLineIfNotEmpty();
    _builder.append("BEGIN");
    _builder.append("\n");
    _builder.newLineIfNotEmpty();
    _builder.append("    ");
    _builder.append("IF first_time = TRUE THEN");
    _builder.append("\n", "    ");
    _builder.append(" ");
    _builder.newLineIfNotEmpty();
    _builder.append("       ");
    _builder.append("cycle_timer <-- get_ms_tick;");
    _builder.append("\n", "       ");
    _builder.append(" ");
    _builder.newLineIfNotEmpty();
    _builder.append("       ");
    _builder.append("execute_model_cycle;");
    _builder.append("\n", "       ");
    _builder.newLineIfNotEmpty();
    _builder.append("       ");
    _builder.append("cycle_state:= 1;");
    _builder.append("\n", "       ");
    _builder.newLineIfNotEmpty();
    _builder.append("       ");
    _builder.append("first_time := FALSE");
    _builder.append("\n", "       ");
    _builder.newLineIfNotEmpty();
    _builder.append("\n");
    _builder.newLineIfNotEmpty();
    _builder.append("    ");
    _builder.append("ELSE");
    _builder.append("\n", "    ");
    _builder.newLineIfNotEmpty();
    _builder.append("        ");
    _builder.append("VAR time_elapsed, cycle_duration IN");
    _builder.append("\n", "        ");
    _builder.append(" ");
    _builder.newLineIfNotEmpty();
    _builder.append("\n");
    _builder.newLineIfNotEmpty();
    _builder.append("            ");
    _builder.append("time_elapsed:(time_elapsed:uint32_t);");
    _builder.append("\n", "            ");
    _builder.newLineIfNotEmpty();
    _builder.append("            ");
    _builder.append("cycle_duration:(cycle_duration:uint32_t);");
    _builder.append("\n", "            ");
    _builder.newLineIfNotEmpty();
    _builder.append("\n");
    _builder.newLineIfNotEmpty();
    _builder.append("            ");
    _builder.append("time_elapsed <-- since(cycle_timer);");
    _builder.append("\n", "            ");
    _builder.newLineIfNotEmpty();
    _builder.append("            ");
    _builder.append("cycle_duration := mul_uint32(SimSMovement_cycleDef,cycle_unit);");
    _builder.append("\n", "            ");
    _builder.newLineIfNotEmpty();
    _builder.append("\n");
    _builder.newLineIfNotEmpty();
    _builder.append("            ");
    _builder.append("IF (cycle_duration <= time_elapsed) THEN");
    _builder.append("\n", "            ");
    _builder.newLineIfNotEmpty();
    _builder.append("\n");
    _builder.newLineIfNotEmpty();
    _builder.append("                ");
    _builder.append("cycle_timer <-- get_ms_tick;");
    _builder.append("\n", "                ");
    _builder.newLineIfNotEmpty();
    _builder.append("                ");
    _builder.append("execute_model_cycle;");
    _builder.append("\n", "                ");
    _builder.newLineIfNotEmpty();
    _builder.append("                ");
    _builder.append("cycle_state:= 1;");
    _builder.append("\n", "                ");
    _builder.newLineIfNotEmpty();
    _builder.append("                ");
    _builder.append("tock");
    _builder.append("\n", "                ");
    _builder.newLineIfNotEmpty();
    _builder.append("            ");
    _builder.append("END");
    _builder.append("\n", "            ");
    _builder.newLineIfNotEmpty();
    _builder.append("        ");
    _builder.append("END");
    _builder.append("\n", "        ");
    _builder.newLineIfNotEmpty();
    _builder.append("    ");
    _builder.append("END");
    _builder.append("\n", "    ");
    _builder.newLineIfNotEmpty();
    _builder.append("END;");
    _builder.append("\n");
    _builder.newLineIfNotEmpty();
    _builder.append("\n");
    _builder.newLineIfNotEmpty();
    _builder.append("reset_outputs =");
    _builder.append("\n");
    _builder.append(" ");
    _builder.newLineIfNotEmpty();
    _builder.append("BEGIN");
    _builder.append("\n");
    _builder.newLineIfNotEmpty();
    _builder.append("    ");
    _builder.append("board_0_O1 := IO_OFF;");
    _builder.append("\n", "    ");
    _builder.newLineIfNotEmpty();
    _builder.append("    ");
    _builder.append("board_0_O2 := IO_OFF");
    _builder.append("\n", "    ");
    _builder.newLineIfNotEmpty();
    _builder.append("END;");
    _builder.append("\n");
    _builder.newLineIfNotEmpty();
    _builder.append("\n");
    _builder.newLineIfNotEmpty();
    _builder.append("read_model_inputs =");
    _builder.append("\n");
    _builder.newLineIfNotEmpty();
    _builder.append("BEGIN");
    _builder.append("\n");
    _builder.newLineIfNotEmpty();
    _builder.append("    ");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("cycle_state := 3");
    _builder.append("\n", "    ");
    _builder.newLineIfNotEmpty();
    _builder.append("END;");
    _builder.append("\n");
    _builder.newLineIfNotEmpty();
    _builder.append("\n");
    _builder.newLineIfNotEmpty();
    _builder.append("write_model_outputs =");
    _builder.append("\n");
    _builder.newLineIfNotEmpty();
    _builder.append("BEGIN");
    _builder.append("\n");
    _builder.newLineIfNotEmpty();
    _builder.append("   ");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("cycle_state:= 4");
    _builder.append("\n", "    ");
    _builder.newLineIfNotEmpty();
    _builder.append("END;");
    _builder.append("\n");
    _builder.newLineIfNotEmpty();
    _builder.append("\n");
    _builder.newLineIfNotEmpty();
    _builder.append("execute_model_cycle =");
    _builder.append("\n");
    _builder.append(" ");
    _builder.newLineIfNotEmpty();
    _builder.append("BEGIN");
    _builder.append("\n");
    _builder.newLineIfNotEmpty();
    _builder.append("    ");
    _builder.append("reset_outputs;");
    _builder.append("\n", "    ");
    _builder.newLineIfNotEmpty();
    _builder.append("    ");
    _builder.append("read_model_inputs;");
    _builder.append("\n", "    ");
    _builder.newLineIfNotEmpty();
    _builder.append("    ");
    _builder.append("//State machine");
    _builder.append("\n", "    ");
    _builder.newLineIfNotEmpty();
    _builder.append("    ");
    _builder.append("write_model_outputs");
    _builder.append("\n", "    ");
    _builder.append(" ");
    _builder.newLineIfNotEmpty();
    _builder.append("END;");
    _builder.append("\n");
    _builder.newLineIfNotEmpty();
    _builder.append("\n");
    _builder.newLineIfNotEmpty();
    _builder.append("elapsed <-- since(timer) =");
    _builder.append("\n");
    _builder.newLineIfNotEmpty();
    _builder.append("BEGIN ");
    _builder.append("\n");
    _builder.append(" ");
    _builder.newLineIfNotEmpty();
    _builder.append("     ");
    _builder.append("elapsed:(elapsed:uint32_t);");
    _builder.append("\n", "     ");
    _builder.newLineIfNotEmpty();
    _builder.append("     ");
    _builder.append("VAR local_time IN ");
    _builder.append("\n", "     ");
    _builder.append(" ");
    _builder.newLineIfNotEmpty();
    _builder.append("         ");
    _builder.append("local_time:(local_time:uint32_t);");
    _builder.append("\n", "         ");
    _builder.newLineIfNotEmpty();
    _builder.append("         ");
    _builder.append("\n", "         ");
    _builder.newLineIfNotEmpty();
    _builder.append("         ");
    _builder.append("local_time <-- get_ms_tick;");
    _builder.append("\n", "         ");
    _builder.newLineIfNotEmpty();
    _builder.append("        ");
    _builder.append("elapsed := sub_uint32(local_time, timer)");
    _builder.append("\n", "        ");
    _builder.newLineIfNotEmpty();
    _builder.append("     ");
    _builder.append("END");
    _builder.append("\n", "     ");
    _builder.newLineIfNotEmpty();
    _builder.append("END;");
    _builder.append("\n");
    _builder.newLineIfNotEmpty();
    _builder.append("\n");
    _builder.append("\t");
    _builder.newLineIfNotEmpty();
    _builder.append("result <-- land(pp,qq) =");
    _builder.append("\n");
    _builder.append("\t ");
    _builder.newLineIfNotEmpty();
    _builder.append("BEGIN");
    _builder.append("\n");
    _builder.append("\t");
    _builder.newLineIfNotEmpty();
    _builder.append("    ");
    _builder.append("result := FALSE;");
    _builder.append("\n", "    ");
    _builder.append("\t");
    _builder.newLineIfNotEmpty();
    _builder.append("    ");
    _builder.append("IF (pp = TRUE) THEN");
    _builder.append("\n", "    ");
    _builder.append("\t ");
    _builder.newLineIfNotEmpty();
    _builder.append("        ");
    _builder.append("IF (qq = TRUE) THEN");
    _builder.append("\n", "        ");
    _builder.append("\t");
    _builder.newLineIfNotEmpty();
    _builder.append("            ");
    _builder.append("result := TRUE");
    _builder.append("\n", "            ");
    _builder.append("\t");
    _builder.newLineIfNotEmpty();
    _builder.append("        ");
    _builder.append("END");
    _builder.append("\n", "        ");
    _builder.append("\t");
    _builder.newLineIfNotEmpty();
    _builder.append("    ");
    _builder.append("END");
    _builder.append("\n", "    ");
    _builder.append("\t");
    _builder.newLineIfNotEmpty();
    _builder.append("END;");
    _builder.append("\n");
    _builder.append("\t");
    _builder.newLineIfNotEmpty();
    _builder.append("\n");
    _builder.newLineIfNotEmpty();
    _builder.append("result <-- lor(pp,qq) =");
    _builder.append("\n");
    _builder.append("\t ");
    _builder.newLineIfNotEmpty();
    _builder.append("BEGIN");
    _builder.append("\n");
    _builder.append("\t");
    _builder.newLineIfNotEmpty();
    _builder.append("    ");
    _builder.append("result := TRUE;");
    _builder.append("\n", "    ");
    _builder.append("\t");
    _builder.newLineIfNotEmpty();
    _builder.append("    ");
    _builder.append("IF (pp = FALSE) THEN ");
    _builder.append("\n", "    ");
    _builder.append("\t");
    _builder.newLineIfNotEmpty();
    _builder.append("        ");
    _builder.append("IF (qq = FALSE) THEN");
    _builder.append("\n", "        ");
    _builder.append("\t");
    _builder.newLineIfNotEmpty();
    _builder.append("            ");
    _builder.append("result := FALSE");
    _builder.append("\n", "            ");
    _builder.append("\t");
    _builder.newLineIfNotEmpty();
    _builder.append("        ");
    _builder.append("END");
    _builder.append("\n", "        ");
    _builder.append("\t");
    _builder.newLineIfNotEmpty();
    _builder.append("    ");
    _builder.append("END");
    _builder.append("\n", "    ");
    _builder.append("\t");
    _builder.newLineIfNotEmpty();
    _builder.append("END;");
    _builder.append("\n");
    _builder.append("\t");
    _builder.newLineIfNotEmpty();
    _builder.append("\n");
    _builder.append("\t    ");
    _builder.newLineIfNotEmpty();
    _builder.append("result <-- lnot(pp) =");
    _builder.append("\n");
    _builder.append("\t ");
    _builder.newLineIfNotEmpty();
    _builder.append("BEGIN");
    _builder.append("\n");
    _builder.append("\t");
    _builder.newLineIfNotEmpty();
    _builder.append("    ");
    _builder.append("result := FALSE;");
    _builder.append("\n", "    ");
    _builder.append("\t");
    _builder.newLineIfNotEmpty();
    _builder.append("    ");
    _builder.append("IF (pp = FALSE) THEN");
    _builder.append("\n", "    ");
    _builder.append("\t ");
    _builder.newLineIfNotEmpty();
    _builder.append("        ");
    _builder.append("result := TRUE");
    _builder.append("\n", "        ");
    _builder.append("\t");
    _builder.newLineIfNotEmpty();
    _builder.append("    ");
    _builder.append("END");
    _builder.append("\n", "    ");
    _builder.append("\t");
    _builder.newLineIfNotEmpty();
    _builder.append("END;");
    _builder.append("\n");
    _builder.newLineIfNotEmpty();
    _builder.append("\n");
    _builder.newLineIfNotEmpty();
    _builder.append("tock =");
    _builder.append("\n");
    _builder.append(" ");
    _builder.newLineIfNotEmpty();
    _builder.append("BEGIN");
    _builder.append("\n");
    _builder.newLineIfNotEmpty();
    _builder.append("    ");
    _builder.append("skip");
    _builder.append("\n", "    ");
    _builder.newLineIfNotEmpty();
    _builder.append("END;");
    _builder.append("\n");
    _builder.newLineIfNotEmpty();
    _builder.append("\n");
    _builder.append("\t");
    _builder.newLineIfNotEmpty();
    _builder.append("po <-- get_board_0_O1 =");
    _builder.append("\n");
    _builder.newLineIfNotEmpty();
    _builder.append("BEGIN");
    _builder.append("\n");
    _builder.newLineIfNotEmpty();
    _builder.append("   ");
    _builder.append("po := board_0_O1");
    _builder.append("\n", "   ");
    _builder.newLineIfNotEmpty();
    _builder.append("END;");
    _builder.append("\n");
    _builder.newLineIfNotEmpty();
    _builder.append("\n");
    _builder.newLineIfNotEmpty();
    _builder.append("po <-- get_board_0_O2 =");
    _builder.append("\n");
    _builder.newLineIfNotEmpty();
    _builder.append("BEGIN");
    _builder.append("\n");
    _builder.newLineIfNotEmpty();
    _builder.append("\t");
    _builder.append("po := board_0_O2");
    _builder.append("\n", "\t");
    _builder.newLineIfNotEmpty();
    _builder.append("END");
    _builder.append("\n");
    _builder.newLineIfNotEmpty();
    _builder.newLine();
    _builder.append("END");
    _builder.newLine();
    return _builder;
  }
  
  public static String mapType(final String robosimType) {
    String _switchResult = null;
    if (robosimType != null) {
      switch (robosimType) {
        case "NAT":
          _switchResult = "uint32_t";
          break;
        case "INT":
          _switchResult = "uint32_t";
          break;
        case "REAL":
          _switchResult = "uint32_t";
          break;
        case "BOOL":
          _switchResult = "BOOL";
          break;
      }
    }
    return _switchResult;
  }
  
  public static String initValue(final Variable v) {
    String _switchResult = null;
    DataType _type = v.getType();
    if (_type != null) {
      switch (_type) {
        case NAT:
        case INT:
        case REAL:
          _switchResult = " 0";
          break;
        case BOOL:
          _switchResult = " FALSE";
          break;
        default:
          break;
      }
    }
    return _switchResult;
  }
}
