/**
 * generated by Xtext 2.25.0
 */
package org.example.domainmodel.tests;

import com.google.inject.Inject;
import org.eclipse.xtext.testing.InjectWith;
import org.eclipse.xtext.testing.extensions.InjectionExtension;
import org.eclipse.xtext.testing.util.ParseHelper;
import org.example.domainmodel.domainmodel.Domainmodel;

/* @ExtendWith(InjectionExtension.class) */@InjectWith(DomainmodelInjectorProvider.class)
@SuppressWarnings("all")
public class DomainmodelParsingTest {
  @Inject
  private ParseHelper<Domainmodel> parseHelper;
  
  /* @Test
   */public void loadModel() {
    throw new Error("Unresolved compilation problems:"
      + "\nThe method or field Assertions is undefined"
      + "\nThe method or field Assertions is undefined"
      + "\nassertNotNull cannot be resolved"
      + "\nassertTrue cannot be resolved");
  }
}
