/*
 * generated by Xtext 2.25.0
 */
package org.example.domainmodel.serializer;

import com.google.inject.Inject;
import java.util.Set;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.xtext.Action;
import org.eclipse.xtext.Parameter;
import org.eclipse.xtext.ParserRule;
import org.eclipse.xtext.serializer.ISerializationContext;
import org.eclipse.xtext.serializer.acceptor.SequenceFeeder;
import org.eclipse.xtext.serializer.sequencer.AbstractDelegatingSemanticSequencer;
import org.eclipse.xtext.serializer.sequencer.ITransientValueService.ValueTransient;
import org.example.domainmodel.domainmodel.Clock;
import org.example.domainmodel.domainmodel.Constant;
import org.example.domainmodel.domainmodel.ContextDecl;
import org.example.domainmodel.domainmodel.CycleDef;
import org.example.domainmodel.domainmodel.DomainmodelPackage;
import org.example.domainmodel.domainmodel.EventDecl;
import org.example.domainmodel.domainmodel.Interface;
import org.example.domainmodel.domainmodel.Model;
import org.example.domainmodel.domainmodel.OperationDecl;
import org.example.domainmodel.domainmodel.Param;
import org.example.domainmodel.domainmodel.Variable;
import org.example.domainmodel.services.DomainmodelGrammarAccess;

@SuppressWarnings("all")
public class DomainmodelSemanticSequencer extends AbstractDelegatingSemanticSequencer {

	@Inject
	private DomainmodelGrammarAccess grammarAccess;
	
	@Override
	public void sequence(ISerializationContext context, EObject semanticObject) {
		EPackage epackage = semanticObject.eClass().getEPackage();
		ParserRule rule = context.getParserRule();
		Action action = context.getAssignedAction();
		Set<Parameter> parameters = context.getEnabledBooleanParameters();
		if (epackage == DomainmodelPackage.eINSTANCE)
			switch (semanticObject.eClass().getClassifierID()) {
			case DomainmodelPackage.CLOCK:
				sequence_Clock(context, (Clock) semanticObject); 
				return; 
			case DomainmodelPackage.CONSTANT:
				sequence_Constant(context, (Constant) semanticObject); 
				return; 
			case DomainmodelPackage.CONTEXT_DECL:
				sequence_ContextDecl(context, (ContextDecl) semanticObject); 
				return; 
			case DomainmodelPackage.CYCLE_DEF:
				sequence_CycleDef(context, (CycleDef) semanticObject); 
				return; 
			case DomainmodelPackage.EVENT_DECL:
				sequence_EventDecl(context, (EventDecl) semanticObject); 
				return; 
			case DomainmodelPackage.INTERFACE:
				sequence_Interface(context, (Interface) semanticObject); 
				return; 
			case DomainmodelPackage.MODEL:
				sequence_Model(context, (Model) semanticObject); 
				return; 
			case DomainmodelPackage.OPERATION_DECL:
				sequence_OperationDecl(context, (OperationDecl) semanticObject); 
				return; 
			case DomainmodelPackage.PARAM:
				sequence_Param(context, (Param) semanticObject); 
				return; 
			case DomainmodelPackage.VARIABLE:
				sequence_Variable(context, (Variable) semanticObject); 
				return; 
			}
		if (errorAcceptor != null)
			errorAcceptor.accept(diagnosticProvider.createInvalidContextOrTypeDiagnostic(semanticObject, context));
	}
	
	/**
	 * Contexts:
	 *     Clock returns Clock
	 *
	 * Constraint:
	 *     (name=ID initialValue=INT?)
	 */
	protected void sequence_Clock(ISerializationContext context, Clock semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Contexts:
	 *     Constant returns Constant
	 *
	 * Constraint:
	 *     (name=ID type=DataType)
	 */
	protected void sequence_Constant(ISerializationContext context, Constant semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, DomainmodelPackage.Literals.CONSTANT__NAME) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, DomainmodelPackage.Literals.CONSTANT__NAME));
			if (transientValues.isValueTransient(semanticObject, DomainmodelPackage.Literals.CONSTANT__TYPE) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, DomainmodelPackage.Literals.CONSTANT__TYPE));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getConstantAccess().getNameIDTerminalRuleCall_1_0(), semanticObject.getName());
		feeder.accept(grammarAccess.getConstantAccess().getTypeDataTypeEnumRuleCall_3_0(), semanticObject.getType());
		feeder.finish();
	}
	
	
	/**
	 * Contexts:
	 *     ContextDecl returns ContextDecl
	 *
	 * Constraint:
	 *     ((kind='input' | kind='output') usedInterfaces+=[Interface|ID] usedInterfaces+=[Interface|ID]* (ops+=OperationDecl | events+=EventDecl)*)
	 */
	protected void sequence_ContextDecl(ISerializationContext context, ContextDecl semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Contexts:
	 *     CycleDef returns CycleDef
	 *
	 * Constraint:
	 *     value=INT
	 */
	protected void sequence_CycleDef(ISerializationContext context, CycleDef semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, DomainmodelPackage.Literals.CYCLE_DEF__VALUE) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, DomainmodelPackage.Literals.CYCLE_DEF__VALUE));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getCycleDefAccess().getValueINTTerminalRuleCall_3_0(), semanticObject.getValue());
		feeder.finish();
	}
	
	
	/**
	 * Contexts:
	 *     EventDecl returns EventDecl
	 *
	 * Constraint:
	 *     name=ID
	 */
	protected void sequence_EventDecl(ISerializationContext context, EventDecl semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, DomainmodelPackage.Literals.EVENT_DECL__NAME) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, DomainmodelPackage.Literals.EVENT_DECL__NAME));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getEventDeclAccess().getNameIDTerminalRuleCall_1_0(), semanticObject.getName());
		feeder.finish();
	}
	
	
	/**
	 * Contexts:
	 *     Interface returns Interface
	 *
	 * Constraint:
	 *     (name=ID (operations+=OperationDecl | events+=EventDecl)*)
	 */
	protected void sequence_Interface(ISerializationContext context, Interface semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Contexts:
	 *     Model returns Model
	 *
	 * Constraint:
	 *     (
	 *         interface+=Interface* 
	 *         name=ID 
	 *         cycleDef=CycleDef? 
	 *         constants+=Constant* 
	 *         variables+=Variable* 
	 *         clock+=Clock* 
	 *         contexts+=ContextDecl*
	 *     )
	 */
	protected void sequence_Model(ISerializationContext context, Model semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Contexts:
	 *     OperationDecl returns OperationDecl
	 *
	 * Constraint:
	 *     (name=ID (params+=Param params+=Param*)?)
	 */
	protected void sequence_OperationDecl(ISerializationContext context, OperationDecl semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Contexts:
	 *     Param returns Param
	 *
	 * Constraint:
	 *     (name=ID type=DataType)
	 */
	protected void sequence_Param(ISerializationContext context, Param semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, DomainmodelPackage.Literals.PARAM__NAME) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, DomainmodelPackage.Literals.PARAM__NAME));
			if (transientValues.isValueTransient(semanticObject, DomainmodelPackage.Literals.PARAM__TYPE) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, DomainmodelPackage.Literals.PARAM__TYPE));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getParamAccess().getNameIDTerminalRuleCall_0_0(), semanticObject.getName());
		feeder.accept(grammarAccess.getParamAccess().getTypeDataTypeEnumRuleCall_2_0(), semanticObject.getType());
		feeder.finish();
	}
	
	
	/**
	 * Contexts:
	 *     Variable returns Variable
	 *
	 * Constraint:
	 *     (name=ID type=DataType initialValue=INT?)
	 */
	protected void sequence_Variable(ISerializationContext context, Variable semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
}
