/**
 * generated by Xtext 2.25.0
 */
package org.example.domainmodel.domainmodel;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Context Decl</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.example.domainmodel.domainmodel.ContextDecl#getKind <em>Kind</em>}</li>
 *   <li>{@link org.example.domainmodel.domainmodel.ContextDecl#getUsedInterfaces <em>Used Interfaces</em>}</li>
 *   <li>{@link org.example.domainmodel.domainmodel.ContextDecl#getOps <em>Ops</em>}</li>
 *   <li>{@link org.example.domainmodel.domainmodel.ContextDecl#getEvents <em>Events</em>}</li>
 * </ul>
 *
 * @see org.example.domainmodel.domainmodel.DomainmodelPackage#getContextDecl()
 * @model
 * @generated
 */
public interface ContextDecl extends EObject
{
  /**
   * Returns the value of the '<em><b>Kind</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Kind</em>' attribute.
   * @see #setKind(String)
   * @see org.example.domainmodel.domainmodel.DomainmodelPackage#getContextDecl_Kind()
   * @model
   * @generated
   */
  String getKind();

  /**
   * Sets the value of the '{@link org.example.domainmodel.domainmodel.ContextDecl#getKind <em>Kind</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Kind</em>' attribute.
   * @see #getKind()
   * @generated
   */
  void setKind(String value);

  /**
   * Returns the value of the '<em><b>Used Interfaces</b></em>' reference list.
   * The list contents are of type {@link org.example.domainmodel.domainmodel.Interface}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Used Interfaces</em>' reference list.
   * @see org.example.domainmodel.domainmodel.DomainmodelPackage#getContextDecl_UsedInterfaces()
   * @model
   * @generated
   */
  EList<Interface> getUsedInterfaces();

  /**
   * Returns the value of the '<em><b>Ops</b></em>' containment reference list.
   * The list contents are of type {@link org.example.domainmodel.domainmodel.OperationDecl}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Ops</em>' containment reference list.
   * @see org.example.domainmodel.domainmodel.DomainmodelPackage#getContextDecl_Ops()
   * @model containment="true"
   * @generated
   */
  EList<OperationDecl> getOps();

  /**
   * Returns the value of the '<em><b>Events</b></em>' containment reference list.
   * The list contents are of type {@link org.example.domainmodel.domainmodel.EventDecl}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Events</em>' containment reference list.
   * @see org.example.domainmodel.domainmodel.DomainmodelPackage#getContextDecl_Events()
   * @model containment="true"
   * @generated
   */
  EList<EventDecl> getEvents();

} // ContextDecl
