grammar org.example.domainmodel.Domainmodel with org.eclipse.xtext.common.Terminals

generate domainmodel "http://www.example.org/domainmodel/Domainmodel"

// Modelo RoboSim

Model:	 
	interface+=Interface* 	
	'stm' name=ID '{'
	    (cycleDef=CycleDef)?
        constants+=Constant*  
        variables+=Variable* 
        clock+=Clock* 
        contexts+=ContextDecl*
    '}'
;
          
Interface:
    'interface' name=ID '{'
        (operations+=OperationDecl | events+=EventDecl )*
    '}'
;

OperationDecl:
   name=ID '(' (params+=Param (',' params+=Param)*)? ')'
;

EventDecl:
    'event' name=ID
;

Param:
    name=ID ':' type=DataType
;

ContextDecl: 
	kind=('input' | 'output') 'context' '{' 
	      'uses' usedInterfaces+=[Interface] (',' usedInterfaces+=[Interface])*
          (ops+=OperationDecl | events+=EventDecl)* 
    '}' 
;

Constant:
    'const' name=ID ':' type=DataType
;

Variable: 
	'var' name=ID ':' type=DataType ('=' initialValue=INT)?
; 

Clock:
    'clock' name=ID ('=' initialValue=INT)?
;

CycleDef:
	'cycleDef' 'cycle' '==' value=INT
;

enum DataType:
    NAT | INT | REAL | BOOL;
    