grammar org.example.domainmodel.Domainmodel with org.eclipse.xtext.common.Terminals

generate domainmodel "http://www.example.org/domainmodel/Domainmodel"

Model:
	'stm' name=ID '{'
        variables+=Variable*
    '}'
;
          
Variable: 
	'var' name=ID ':' type=DataType ('=' initialValue=Value)?
; 

enum DataType:
    NAT | INT | REAL | BOOL;
    
Value:
    value=('NAT' | 'INT' | 'REAL' | 'true' | 'false')
;