/**
 * generated by Xtext 2.25.0
 */
package org.example.domainmodel.domainmodel.impl;

import java.util.Collection;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.eclipse.emf.ecore.util.EObjectContainmentEList;
import org.eclipse.emf.ecore.util.EObjectResolvingEList;
import org.eclipse.emf.ecore.util.InternalEList;

import org.example.domainmodel.domainmodel.ContextDecl;
import org.example.domainmodel.domainmodel.DomainmodelPackage;
import org.example.domainmodel.domainmodel.EventDecl;
import org.example.domainmodel.domainmodel.Interface;
import org.example.domainmodel.domainmodel.OperationDecl;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Context Decl</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link org.example.domainmodel.domainmodel.impl.ContextDeclImpl#getKind <em>Kind</em>}</li>
 *   <li>{@link org.example.domainmodel.domainmodel.impl.ContextDeclImpl#getUsedInterfaces <em>Used Interfaces</em>}</li>
 *   <li>{@link org.example.domainmodel.domainmodel.impl.ContextDeclImpl#getOps <em>Ops</em>}</li>
 *   <li>{@link org.example.domainmodel.domainmodel.impl.ContextDeclImpl#getEvents <em>Events</em>}</li>
 * </ul>
 *
 * @generated
 */
public class ContextDeclImpl extends MinimalEObjectImpl.Container implements ContextDecl
{
  /**
   * The default value of the '{@link #getKind() <em>Kind</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getKind()
   * @generated
   * @ordered
   */
  protected static final String KIND_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getKind() <em>Kind</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getKind()
   * @generated
   * @ordered
   */
  protected String kind = KIND_EDEFAULT;

  /**
   * The cached value of the '{@link #getUsedInterfaces() <em>Used Interfaces</em>}' reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getUsedInterfaces()
   * @generated
   * @ordered
   */
  protected EList<Interface> usedInterfaces;

  /**
   * The cached value of the '{@link #getOps() <em>Ops</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getOps()
   * @generated
   * @ordered
   */
  protected EList<OperationDecl> ops;

  /**
   * The cached value of the '{@link #getEvents() <em>Events</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getEvents()
   * @generated
   * @ordered
   */
  protected EList<EventDecl> events;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected ContextDeclImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return DomainmodelPackage.Literals.CONTEXT_DECL;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getKind()
  {
    return kind;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setKind(String newKind)
  {
    String oldKind = kind;
    kind = newKind;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, DomainmodelPackage.CONTEXT_DECL__KIND, oldKind, kind));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<Interface> getUsedInterfaces()
  {
    if (usedInterfaces == null)
    {
      usedInterfaces = new EObjectResolvingEList<Interface>(Interface.class, this, DomainmodelPackage.CONTEXT_DECL__USED_INTERFACES);
    }
    return usedInterfaces;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<OperationDecl> getOps()
  {
    if (ops == null)
    {
      ops = new EObjectContainmentEList<OperationDecl>(OperationDecl.class, this, DomainmodelPackage.CONTEXT_DECL__OPS);
    }
    return ops;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<EventDecl> getEvents()
  {
    if (events == null)
    {
      events = new EObjectContainmentEList<EventDecl>(EventDecl.class, this, DomainmodelPackage.CONTEXT_DECL__EVENTS);
    }
    return events;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case DomainmodelPackage.CONTEXT_DECL__OPS:
        return ((InternalEList<?>)getOps()).basicRemove(otherEnd, msgs);
      case DomainmodelPackage.CONTEXT_DECL__EVENTS:
        return ((InternalEList<?>)getEvents()).basicRemove(otherEnd, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case DomainmodelPackage.CONTEXT_DECL__KIND:
        return getKind();
      case DomainmodelPackage.CONTEXT_DECL__USED_INTERFACES:
        return getUsedInterfaces();
      case DomainmodelPackage.CONTEXT_DECL__OPS:
        return getOps();
      case DomainmodelPackage.CONTEXT_DECL__EVENTS:
        return getEvents();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @SuppressWarnings("unchecked")
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case DomainmodelPackage.CONTEXT_DECL__KIND:
        setKind((String)newValue);
        return;
      case DomainmodelPackage.CONTEXT_DECL__USED_INTERFACES:
        getUsedInterfaces().clear();
        getUsedInterfaces().addAll((Collection<? extends Interface>)newValue);
        return;
      case DomainmodelPackage.CONTEXT_DECL__OPS:
        getOps().clear();
        getOps().addAll((Collection<? extends OperationDecl>)newValue);
        return;
      case DomainmodelPackage.CONTEXT_DECL__EVENTS:
        getEvents().clear();
        getEvents().addAll((Collection<? extends EventDecl>)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case DomainmodelPackage.CONTEXT_DECL__KIND:
        setKind(KIND_EDEFAULT);
        return;
      case DomainmodelPackage.CONTEXT_DECL__USED_INTERFACES:
        getUsedInterfaces().clear();
        return;
      case DomainmodelPackage.CONTEXT_DECL__OPS:
        getOps().clear();
        return;
      case DomainmodelPackage.CONTEXT_DECL__EVENTS:
        getEvents().clear();
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case DomainmodelPackage.CONTEXT_DECL__KIND:
        return KIND_EDEFAULT == null ? kind != null : !KIND_EDEFAULT.equals(kind);
      case DomainmodelPackage.CONTEXT_DECL__USED_INTERFACES:
        return usedInterfaces != null && !usedInterfaces.isEmpty();
      case DomainmodelPackage.CONTEXT_DECL__OPS:
        return ops != null && !ops.isEmpty();
      case DomainmodelPackage.CONTEXT_DECL__EVENTS:
        return events != null && !events.isEmpty();
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuilder result = new StringBuilder(super.toString());
    result.append(" (kind: ");
    result.append(kind);
    result.append(')');
    return result.toString();
  }

} //ContextDeclImpl
