/*
 * generated by Xtext 2.25.0
 */
grammar InternalDomainmodel;

options {
	superClass=AbstractInternalContentAssistParser;
}

@lexer::header {
package org.example.domainmodel.ide.contentassist.antlr.internal;

// Hack: Use our own Lexer superclass by means of import. 
// Currently there is no other way to specify the superclass for the lexer.
import org.eclipse.xtext.ide.editor.contentassist.antlr.internal.Lexer;
}

@parser::header {
package org.example.domainmodel.ide.contentassist.antlr.internal;

import java.io.InputStream;
import org.eclipse.xtext.*;
import org.eclipse.xtext.parser.*;
import org.eclipse.xtext.parser.impl.*;
import org.eclipse.emf.ecore.util.EcoreUtil;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import org.eclipse.xtext.parser.antlr.XtextTokenStream.HiddenTokens;
import org.eclipse.xtext.ide.editor.contentassist.antlr.internal.AbstractInternalContentAssistParser;
import org.eclipse.xtext.ide.editor.contentassist.antlr.internal.DFA;
import org.example.domainmodel.services.DomainmodelGrammarAccess;

}
@parser::members {
	private DomainmodelGrammarAccess grammarAccess;

	public void setGrammarAccess(DomainmodelGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}

	@Override
	protected Grammar getGrammar() {
		return grammarAccess.getGrammar();
	}

	@Override
	protected String getValueForTokenName(String tokenName) {
		return tokenName;
	}
}

// Entry rule entryRuleModel
entryRuleModel
:
{ before(grammarAccess.getModelRule()); }
	 ruleModel
{ after(grammarAccess.getModelRule()); } 
	 EOF 
;

// Rule Model
ruleModel 
	@init {
		int stackSize = keepStackSize();
	}
	:
	(
		{ before(grammarAccess.getModelAccess().getGroup()); }
		(rule__Model__Group__0)
		{ after(grammarAccess.getModelAccess().getGroup()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

// Entry rule entryRuleInterface
entryRuleInterface
:
{ before(grammarAccess.getInterfaceRule()); }
	 ruleInterface
{ after(grammarAccess.getInterfaceRule()); } 
	 EOF 
;

// Rule Interface
ruleInterface 
	@init {
		int stackSize = keepStackSize();
	}
	:
	(
		{ before(grammarAccess.getInterfaceAccess().getGroup()); }
		(rule__Interface__Group__0)
		{ after(grammarAccess.getInterfaceAccess().getGroup()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

// Entry rule entryRuleOperationDecl
entryRuleOperationDecl
:
{ before(grammarAccess.getOperationDeclRule()); }
	 ruleOperationDecl
{ after(grammarAccess.getOperationDeclRule()); } 
	 EOF 
;

// Rule OperationDecl
ruleOperationDecl 
	@init {
		int stackSize = keepStackSize();
	}
	:
	(
		{ before(grammarAccess.getOperationDeclAccess().getGroup()); }
		(rule__OperationDecl__Group__0)
		{ after(grammarAccess.getOperationDeclAccess().getGroup()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

// Entry rule entryRuleEventDecl
entryRuleEventDecl
:
{ before(grammarAccess.getEventDeclRule()); }
	 ruleEventDecl
{ after(grammarAccess.getEventDeclRule()); } 
	 EOF 
;

// Rule EventDecl
ruleEventDecl 
	@init {
		int stackSize = keepStackSize();
	}
	:
	(
		{ before(grammarAccess.getEventDeclAccess().getGroup()); }
		(rule__EventDecl__Group__0)
		{ after(grammarAccess.getEventDeclAccess().getGroup()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

// Entry rule entryRuleParam
entryRuleParam
:
{ before(grammarAccess.getParamRule()); }
	 ruleParam
{ after(grammarAccess.getParamRule()); } 
	 EOF 
;

// Rule Param
ruleParam 
	@init {
		int stackSize = keepStackSize();
	}
	:
	(
		{ before(grammarAccess.getParamAccess().getGroup()); }
		(rule__Param__Group__0)
		{ after(grammarAccess.getParamAccess().getGroup()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

// Entry rule entryRuleContextDecl
entryRuleContextDecl
:
{ before(grammarAccess.getContextDeclRule()); }
	 ruleContextDecl
{ after(grammarAccess.getContextDeclRule()); } 
	 EOF 
;

// Rule ContextDecl
ruleContextDecl 
	@init {
		int stackSize = keepStackSize();
	}
	:
	(
		{ before(grammarAccess.getContextDeclAccess().getGroup()); }
		(rule__ContextDecl__Group__0)
		{ after(grammarAccess.getContextDeclAccess().getGroup()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

// Entry rule entryRuleConstant
entryRuleConstant
:
{ before(grammarAccess.getConstantRule()); }
	 ruleConstant
{ after(grammarAccess.getConstantRule()); } 
	 EOF 
;

// Rule Constant
ruleConstant 
	@init {
		int stackSize = keepStackSize();
	}
	:
	(
		{ before(grammarAccess.getConstantAccess().getGroup()); }
		(rule__Constant__Group__0)
		{ after(grammarAccess.getConstantAccess().getGroup()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

// Entry rule entryRuleVariable
entryRuleVariable
:
{ before(grammarAccess.getVariableRule()); }
	 ruleVariable
{ after(grammarAccess.getVariableRule()); } 
	 EOF 
;

// Rule Variable
ruleVariable 
	@init {
		int stackSize = keepStackSize();
	}
	:
	(
		{ before(grammarAccess.getVariableAccess().getGroup()); }
		(rule__Variable__Group__0)
		{ after(grammarAccess.getVariableAccess().getGroup()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

// Entry rule entryRuleClock
entryRuleClock
:
{ before(grammarAccess.getClockRule()); }
	 ruleClock
{ after(grammarAccess.getClockRule()); } 
	 EOF 
;

// Rule Clock
ruleClock 
	@init {
		int stackSize = keepStackSize();
	}
	:
	(
		{ before(grammarAccess.getClockAccess().getGroup()); }
		(rule__Clock__Group__0)
		{ after(grammarAccess.getClockAccess().getGroup()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

// Entry rule entryRuleCycleDef
entryRuleCycleDef
:
{ before(grammarAccess.getCycleDefRule()); }
	 ruleCycleDef
{ after(grammarAccess.getCycleDefRule()); } 
	 EOF 
;

// Rule CycleDef
ruleCycleDef 
	@init {
		int stackSize = keepStackSize();
	}
	:
	(
		{ before(grammarAccess.getCycleDefAccess().getGroup()); }
		(rule__CycleDef__Group__0)
		{ after(grammarAccess.getCycleDefAccess().getGroup()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

// Rule DataType
ruleDataType
	@init {
		int stackSize = keepStackSize();
	}
:
	(
		{ before(grammarAccess.getDataTypeAccess().getAlternatives()); }
		(rule__DataType__Alternatives)
		{ after(grammarAccess.getDataTypeAccess().getAlternatives()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

rule__Interface__Alternatives_3
	@init {
		int stackSize = keepStackSize();
	}
:
	(
		{ before(grammarAccess.getInterfaceAccess().getOperationsAssignment_3_0()); }
		(rule__Interface__OperationsAssignment_3_0)
		{ after(grammarAccess.getInterfaceAccess().getOperationsAssignment_3_0()); }
	)
	|
	(
		{ before(grammarAccess.getInterfaceAccess().getEventsAssignment_3_1()); }
		(rule__Interface__EventsAssignment_3_1)
		{ after(grammarAccess.getInterfaceAccess().getEventsAssignment_3_1()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

rule__ContextDecl__KindAlternatives_0_0
	@init {
		int stackSize = keepStackSize();
	}
:
	(
		{ before(grammarAccess.getContextDeclAccess().getKindInputKeyword_0_0_0()); }
		'input'
		{ after(grammarAccess.getContextDeclAccess().getKindInputKeyword_0_0_0()); }
	)
	|
	(
		{ before(grammarAccess.getContextDeclAccess().getKindOutputKeyword_0_0_1()); }
		'output'
		{ after(grammarAccess.getContextDeclAccess().getKindOutputKeyword_0_0_1()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

rule__ContextDecl__Alternatives_6
	@init {
		int stackSize = keepStackSize();
	}
:
	(
		{ before(grammarAccess.getContextDeclAccess().getOpsAssignment_6_0()); }
		(rule__ContextDecl__OpsAssignment_6_0)
		{ after(grammarAccess.getContextDeclAccess().getOpsAssignment_6_0()); }
	)
	|
	(
		{ before(grammarAccess.getContextDeclAccess().getEventsAssignment_6_1()); }
		(rule__ContextDecl__EventsAssignment_6_1)
		{ after(grammarAccess.getContextDeclAccess().getEventsAssignment_6_1()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

rule__DataType__Alternatives
	@init {
		int stackSize = keepStackSize();
	}
:
	(
		{ before(grammarAccess.getDataTypeAccess().getNATEnumLiteralDeclaration_0()); }
		('NAT')
		{ after(grammarAccess.getDataTypeAccess().getNATEnumLiteralDeclaration_0()); }
	)
	|
	(
		{ before(grammarAccess.getDataTypeAccess().getINTEnumLiteralDeclaration_1()); }
		('INT')
		{ after(grammarAccess.getDataTypeAccess().getINTEnumLiteralDeclaration_1()); }
	)
	|
	(
		{ before(grammarAccess.getDataTypeAccess().getREALEnumLiteralDeclaration_2()); }
		('REAL')
		{ after(grammarAccess.getDataTypeAccess().getREALEnumLiteralDeclaration_2()); }
	)
	|
	(
		{ before(grammarAccess.getDataTypeAccess().getBOOLEnumLiteralDeclaration_3()); }
		('BOOL')
		{ after(grammarAccess.getDataTypeAccess().getBOOLEnumLiteralDeclaration_3()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

rule__Model__Group__0
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Model__Group__0__Impl
	rule__Model__Group__1
;
finally {
	restoreStackSize(stackSize);
}

rule__Model__Group__0__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getModelAccess().getInterfaceAssignment_0()); }
	(rule__Model__InterfaceAssignment_0)*
	{ after(grammarAccess.getModelAccess().getInterfaceAssignment_0()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__Model__Group__1
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Model__Group__1__Impl
	rule__Model__Group__2
;
finally {
	restoreStackSize(stackSize);
}

rule__Model__Group__1__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getModelAccess().getStmKeyword_1()); }
	'stm'
	{ after(grammarAccess.getModelAccess().getStmKeyword_1()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__Model__Group__2
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Model__Group__2__Impl
	rule__Model__Group__3
;
finally {
	restoreStackSize(stackSize);
}

rule__Model__Group__2__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getModelAccess().getNameAssignment_2()); }
	(rule__Model__NameAssignment_2)
	{ after(grammarAccess.getModelAccess().getNameAssignment_2()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__Model__Group__3
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Model__Group__3__Impl
	rule__Model__Group__4
;
finally {
	restoreStackSize(stackSize);
}

rule__Model__Group__3__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getModelAccess().getLeftCurlyBracketKeyword_3()); }
	'{'
	{ after(grammarAccess.getModelAccess().getLeftCurlyBracketKeyword_3()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__Model__Group__4
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Model__Group__4__Impl
	rule__Model__Group__5
;
finally {
	restoreStackSize(stackSize);
}

rule__Model__Group__4__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getModelAccess().getCycleDefAssignment_4()); }
	(rule__Model__CycleDefAssignment_4)?
	{ after(grammarAccess.getModelAccess().getCycleDefAssignment_4()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__Model__Group__5
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Model__Group__5__Impl
	rule__Model__Group__6
;
finally {
	restoreStackSize(stackSize);
}

rule__Model__Group__5__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getModelAccess().getConstantsAssignment_5()); }
	(rule__Model__ConstantsAssignment_5)*
	{ after(grammarAccess.getModelAccess().getConstantsAssignment_5()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__Model__Group__6
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Model__Group__6__Impl
	rule__Model__Group__7
;
finally {
	restoreStackSize(stackSize);
}

rule__Model__Group__6__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getModelAccess().getVariablesAssignment_6()); }
	(rule__Model__VariablesAssignment_6)*
	{ after(grammarAccess.getModelAccess().getVariablesAssignment_6()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__Model__Group__7
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Model__Group__7__Impl
	rule__Model__Group__8
;
finally {
	restoreStackSize(stackSize);
}

rule__Model__Group__7__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getModelAccess().getClockAssignment_7()); }
	(rule__Model__ClockAssignment_7)*
	{ after(grammarAccess.getModelAccess().getClockAssignment_7()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__Model__Group__8
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Model__Group__8__Impl
	rule__Model__Group__9
;
finally {
	restoreStackSize(stackSize);
}

rule__Model__Group__8__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getModelAccess().getContextsAssignment_8()); }
	(rule__Model__ContextsAssignment_8)*
	{ after(grammarAccess.getModelAccess().getContextsAssignment_8()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__Model__Group__9
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Model__Group__9__Impl
;
finally {
	restoreStackSize(stackSize);
}

rule__Model__Group__9__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getModelAccess().getRightCurlyBracketKeyword_9()); }
	'}'
	{ after(grammarAccess.getModelAccess().getRightCurlyBracketKeyword_9()); }
)
;
finally {
	restoreStackSize(stackSize);
}


rule__Interface__Group__0
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Interface__Group__0__Impl
	rule__Interface__Group__1
;
finally {
	restoreStackSize(stackSize);
}

rule__Interface__Group__0__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getInterfaceAccess().getInterfaceKeyword_0()); }
	'interface'
	{ after(grammarAccess.getInterfaceAccess().getInterfaceKeyword_0()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__Interface__Group__1
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Interface__Group__1__Impl
	rule__Interface__Group__2
;
finally {
	restoreStackSize(stackSize);
}

rule__Interface__Group__1__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getInterfaceAccess().getNameAssignment_1()); }
	(rule__Interface__NameAssignment_1)
	{ after(grammarAccess.getInterfaceAccess().getNameAssignment_1()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__Interface__Group__2
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Interface__Group__2__Impl
	rule__Interface__Group__3
;
finally {
	restoreStackSize(stackSize);
}

rule__Interface__Group__2__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getInterfaceAccess().getLeftCurlyBracketKeyword_2()); }
	'{'
	{ after(grammarAccess.getInterfaceAccess().getLeftCurlyBracketKeyword_2()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__Interface__Group__3
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Interface__Group__3__Impl
	rule__Interface__Group__4
;
finally {
	restoreStackSize(stackSize);
}

rule__Interface__Group__3__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getInterfaceAccess().getAlternatives_3()); }
	(rule__Interface__Alternatives_3)*
	{ after(grammarAccess.getInterfaceAccess().getAlternatives_3()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__Interface__Group__4
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Interface__Group__4__Impl
;
finally {
	restoreStackSize(stackSize);
}

rule__Interface__Group__4__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getInterfaceAccess().getRightCurlyBracketKeyword_4()); }
	'}'
	{ after(grammarAccess.getInterfaceAccess().getRightCurlyBracketKeyword_4()); }
)
;
finally {
	restoreStackSize(stackSize);
}


rule__OperationDecl__Group__0
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__OperationDecl__Group__0__Impl
	rule__OperationDecl__Group__1
;
finally {
	restoreStackSize(stackSize);
}

rule__OperationDecl__Group__0__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getOperationDeclAccess().getNameAssignment_0()); }
	(rule__OperationDecl__NameAssignment_0)
	{ after(grammarAccess.getOperationDeclAccess().getNameAssignment_0()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__OperationDecl__Group__1
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__OperationDecl__Group__1__Impl
	rule__OperationDecl__Group__2
;
finally {
	restoreStackSize(stackSize);
}

rule__OperationDecl__Group__1__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getOperationDeclAccess().getLeftParenthesisKeyword_1()); }
	'('
	{ after(grammarAccess.getOperationDeclAccess().getLeftParenthesisKeyword_1()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__OperationDecl__Group__2
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__OperationDecl__Group__2__Impl
	rule__OperationDecl__Group__3
;
finally {
	restoreStackSize(stackSize);
}

rule__OperationDecl__Group__2__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getOperationDeclAccess().getGroup_2()); }
	(rule__OperationDecl__Group_2__0)?
	{ after(grammarAccess.getOperationDeclAccess().getGroup_2()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__OperationDecl__Group__3
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__OperationDecl__Group__3__Impl
;
finally {
	restoreStackSize(stackSize);
}

rule__OperationDecl__Group__3__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getOperationDeclAccess().getRightParenthesisKeyword_3()); }
	')'
	{ after(grammarAccess.getOperationDeclAccess().getRightParenthesisKeyword_3()); }
)
;
finally {
	restoreStackSize(stackSize);
}


rule__OperationDecl__Group_2__0
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__OperationDecl__Group_2__0__Impl
	rule__OperationDecl__Group_2__1
;
finally {
	restoreStackSize(stackSize);
}

rule__OperationDecl__Group_2__0__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getOperationDeclAccess().getParamsAssignment_2_0()); }
	(rule__OperationDecl__ParamsAssignment_2_0)
	{ after(grammarAccess.getOperationDeclAccess().getParamsAssignment_2_0()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__OperationDecl__Group_2__1
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__OperationDecl__Group_2__1__Impl
;
finally {
	restoreStackSize(stackSize);
}

rule__OperationDecl__Group_2__1__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getOperationDeclAccess().getGroup_2_1()); }
	(rule__OperationDecl__Group_2_1__0)*
	{ after(grammarAccess.getOperationDeclAccess().getGroup_2_1()); }
)
;
finally {
	restoreStackSize(stackSize);
}


rule__OperationDecl__Group_2_1__0
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__OperationDecl__Group_2_1__0__Impl
	rule__OperationDecl__Group_2_1__1
;
finally {
	restoreStackSize(stackSize);
}

rule__OperationDecl__Group_2_1__0__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getOperationDeclAccess().getCommaKeyword_2_1_0()); }
	','
	{ after(grammarAccess.getOperationDeclAccess().getCommaKeyword_2_1_0()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__OperationDecl__Group_2_1__1
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__OperationDecl__Group_2_1__1__Impl
;
finally {
	restoreStackSize(stackSize);
}

rule__OperationDecl__Group_2_1__1__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getOperationDeclAccess().getParamsAssignment_2_1_1()); }
	(rule__OperationDecl__ParamsAssignment_2_1_1)
	{ after(grammarAccess.getOperationDeclAccess().getParamsAssignment_2_1_1()); }
)
;
finally {
	restoreStackSize(stackSize);
}


rule__EventDecl__Group__0
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__EventDecl__Group__0__Impl
	rule__EventDecl__Group__1
;
finally {
	restoreStackSize(stackSize);
}

rule__EventDecl__Group__0__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getEventDeclAccess().getEventKeyword_0()); }
	'event'
	{ after(grammarAccess.getEventDeclAccess().getEventKeyword_0()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__EventDecl__Group__1
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__EventDecl__Group__1__Impl
;
finally {
	restoreStackSize(stackSize);
}

rule__EventDecl__Group__1__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getEventDeclAccess().getNameAssignment_1()); }
	(rule__EventDecl__NameAssignment_1)
	{ after(grammarAccess.getEventDeclAccess().getNameAssignment_1()); }
)
;
finally {
	restoreStackSize(stackSize);
}


rule__Param__Group__0
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Param__Group__0__Impl
	rule__Param__Group__1
;
finally {
	restoreStackSize(stackSize);
}

rule__Param__Group__0__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getParamAccess().getNameAssignment_0()); }
	(rule__Param__NameAssignment_0)
	{ after(grammarAccess.getParamAccess().getNameAssignment_0()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__Param__Group__1
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Param__Group__1__Impl
	rule__Param__Group__2
;
finally {
	restoreStackSize(stackSize);
}

rule__Param__Group__1__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getParamAccess().getColonKeyword_1()); }
	':'
	{ after(grammarAccess.getParamAccess().getColonKeyword_1()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__Param__Group__2
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Param__Group__2__Impl
;
finally {
	restoreStackSize(stackSize);
}

rule__Param__Group__2__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getParamAccess().getTypeAssignment_2()); }
	(rule__Param__TypeAssignment_2)
	{ after(grammarAccess.getParamAccess().getTypeAssignment_2()); }
)
;
finally {
	restoreStackSize(stackSize);
}


rule__ContextDecl__Group__0
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__ContextDecl__Group__0__Impl
	rule__ContextDecl__Group__1
;
finally {
	restoreStackSize(stackSize);
}

rule__ContextDecl__Group__0__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getContextDeclAccess().getKindAssignment_0()); }
	(rule__ContextDecl__KindAssignment_0)
	{ after(grammarAccess.getContextDeclAccess().getKindAssignment_0()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__ContextDecl__Group__1
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__ContextDecl__Group__1__Impl
	rule__ContextDecl__Group__2
;
finally {
	restoreStackSize(stackSize);
}

rule__ContextDecl__Group__1__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getContextDeclAccess().getContextKeyword_1()); }
	'context'
	{ after(grammarAccess.getContextDeclAccess().getContextKeyword_1()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__ContextDecl__Group__2
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__ContextDecl__Group__2__Impl
	rule__ContextDecl__Group__3
;
finally {
	restoreStackSize(stackSize);
}

rule__ContextDecl__Group__2__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getContextDeclAccess().getLeftCurlyBracketKeyword_2()); }
	'{'
	{ after(grammarAccess.getContextDeclAccess().getLeftCurlyBracketKeyword_2()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__ContextDecl__Group__3
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__ContextDecl__Group__3__Impl
	rule__ContextDecl__Group__4
;
finally {
	restoreStackSize(stackSize);
}

rule__ContextDecl__Group__3__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getContextDeclAccess().getUsesKeyword_3()); }
	'uses'
	{ after(grammarAccess.getContextDeclAccess().getUsesKeyword_3()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__ContextDecl__Group__4
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__ContextDecl__Group__4__Impl
	rule__ContextDecl__Group__5
;
finally {
	restoreStackSize(stackSize);
}

rule__ContextDecl__Group__4__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getContextDeclAccess().getUsedInterfacesAssignment_4()); }
	(rule__ContextDecl__UsedInterfacesAssignment_4)
	{ after(grammarAccess.getContextDeclAccess().getUsedInterfacesAssignment_4()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__ContextDecl__Group__5
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__ContextDecl__Group__5__Impl
	rule__ContextDecl__Group__6
;
finally {
	restoreStackSize(stackSize);
}

rule__ContextDecl__Group__5__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getContextDeclAccess().getGroup_5()); }
	(rule__ContextDecl__Group_5__0)*
	{ after(grammarAccess.getContextDeclAccess().getGroup_5()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__ContextDecl__Group__6
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__ContextDecl__Group__6__Impl
	rule__ContextDecl__Group__7
;
finally {
	restoreStackSize(stackSize);
}

rule__ContextDecl__Group__6__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getContextDeclAccess().getAlternatives_6()); }
	(rule__ContextDecl__Alternatives_6)*
	{ after(grammarAccess.getContextDeclAccess().getAlternatives_6()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__ContextDecl__Group__7
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__ContextDecl__Group__7__Impl
;
finally {
	restoreStackSize(stackSize);
}

rule__ContextDecl__Group__7__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getContextDeclAccess().getRightCurlyBracketKeyword_7()); }
	'}'
	{ after(grammarAccess.getContextDeclAccess().getRightCurlyBracketKeyword_7()); }
)
;
finally {
	restoreStackSize(stackSize);
}


rule__ContextDecl__Group_5__0
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__ContextDecl__Group_5__0__Impl
	rule__ContextDecl__Group_5__1
;
finally {
	restoreStackSize(stackSize);
}

rule__ContextDecl__Group_5__0__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getContextDeclAccess().getCommaKeyword_5_0()); }
	','
	{ after(grammarAccess.getContextDeclAccess().getCommaKeyword_5_0()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__ContextDecl__Group_5__1
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__ContextDecl__Group_5__1__Impl
;
finally {
	restoreStackSize(stackSize);
}

rule__ContextDecl__Group_5__1__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getContextDeclAccess().getUsedInterfacesAssignment_5_1()); }
	(rule__ContextDecl__UsedInterfacesAssignment_5_1)
	{ after(grammarAccess.getContextDeclAccess().getUsedInterfacesAssignment_5_1()); }
)
;
finally {
	restoreStackSize(stackSize);
}


rule__Constant__Group__0
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Constant__Group__0__Impl
	rule__Constant__Group__1
;
finally {
	restoreStackSize(stackSize);
}

rule__Constant__Group__0__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getConstantAccess().getConstKeyword_0()); }
	'const'
	{ after(grammarAccess.getConstantAccess().getConstKeyword_0()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__Constant__Group__1
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Constant__Group__1__Impl
	rule__Constant__Group__2
;
finally {
	restoreStackSize(stackSize);
}

rule__Constant__Group__1__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getConstantAccess().getNameAssignment_1()); }
	(rule__Constant__NameAssignment_1)
	{ after(grammarAccess.getConstantAccess().getNameAssignment_1()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__Constant__Group__2
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Constant__Group__2__Impl
	rule__Constant__Group__3
;
finally {
	restoreStackSize(stackSize);
}

rule__Constant__Group__2__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getConstantAccess().getColonKeyword_2()); }
	':'
	{ after(grammarAccess.getConstantAccess().getColonKeyword_2()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__Constant__Group__3
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Constant__Group__3__Impl
;
finally {
	restoreStackSize(stackSize);
}

rule__Constant__Group__3__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getConstantAccess().getTypeAssignment_3()); }
	(rule__Constant__TypeAssignment_3)
	{ after(grammarAccess.getConstantAccess().getTypeAssignment_3()); }
)
;
finally {
	restoreStackSize(stackSize);
}


rule__Variable__Group__0
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Variable__Group__0__Impl
	rule__Variable__Group__1
;
finally {
	restoreStackSize(stackSize);
}

rule__Variable__Group__0__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getVariableAccess().getVarKeyword_0()); }
	'var'
	{ after(grammarAccess.getVariableAccess().getVarKeyword_0()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__Variable__Group__1
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Variable__Group__1__Impl
	rule__Variable__Group__2
;
finally {
	restoreStackSize(stackSize);
}

rule__Variable__Group__1__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getVariableAccess().getNameAssignment_1()); }
	(rule__Variable__NameAssignment_1)
	{ after(grammarAccess.getVariableAccess().getNameAssignment_1()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__Variable__Group__2
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Variable__Group__2__Impl
	rule__Variable__Group__3
;
finally {
	restoreStackSize(stackSize);
}

rule__Variable__Group__2__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getVariableAccess().getColonKeyword_2()); }
	':'
	{ after(grammarAccess.getVariableAccess().getColonKeyword_2()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__Variable__Group__3
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Variable__Group__3__Impl
	rule__Variable__Group__4
;
finally {
	restoreStackSize(stackSize);
}

rule__Variable__Group__3__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getVariableAccess().getTypeAssignment_3()); }
	(rule__Variable__TypeAssignment_3)
	{ after(grammarAccess.getVariableAccess().getTypeAssignment_3()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__Variable__Group__4
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Variable__Group__4__Impl
;
finally {
	restoreStackSize(stackSize);
}

rule__Variable__Group__4__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getVariableAccess().getGroup_4()); }
	(rule__Variable__Group_4__0)?
	{ after(grammarAccess.getVariableAccess().getGroup_4()); }
)
;
finally {
	restoreStackSize(stackSize);
}


rule__Variable__Group_4__0
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Variable__Group_4__0__Impl
	rule__Variable__Group_4__1
;
finally {
	restoreStackSize(stackSize);
}

rule__Variable__Group_4__0__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getVariableAccess().getEqualsSignKeyword_4_0()); }
	'='
	{ after(grammarAccess.getVariableAccess().getEqualsSignKeyword_4_0()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__Variable__Group_4__1
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Variable__Group_4__1__Impl
;
finally {
	restoreStackSize(stackSize);
}

rule__Variable__Group_4__1__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getVariableAccess().getInitialValueAssignment_4_1()); }
	(rule__Variable__InitialValueAssignment_4_1)
	{ after(grammarAccess.getVariableAccess().getInitialValueAssignment_4_1()); }
)
;
finally {
	restoreStackSize(stackSize);
}


rule__Clock__Group__0
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Clock__Group__0__Impl
	rule__Clock__Group__1
;
finally {
	restoreStackSize(stackSize);
}

rule__Clock__Group__0__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getClockAccess().getClockKeyword_0()); }
	'clock'
	{ after(grammarAccess.getClockAccess().getClockKeyword_0()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__Clock__Group__1
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Clock__Group__1__Impl
	rule__Clock__Group__2
;
finally {
	restoreStackSize(stackSize);
}

rule__Clock__Group__1__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getClockAccess().getNameAssignment_1()); }
	(rule__Clock__NameAssignment_1)
	{ after(grammarAccess.getClockAccess().getNameAssignment_1()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__Clock__Group__2
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Clock__Group__2__Impl
;
finally {
	restoreStackSize(stackSize);
}

rule__Clock__Group__2__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getClockAccess().getGroup_2()); }
	(rule__Clock__Group_2__0)?
	{ after(grammarAccess.getClockAccess().getGroup_2()); }
)
;
finally {
	restoreStackSize(stackSize);
}


rule__Clock__Group_2__0
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Clock__Group_2__0__Impl
	rule__Clock__Group_2__1
;
finally {
	restoreStackSize(stackSize);
}

rule__Clock__Group_2__0__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getClockAccess().getEqualsSignKeyword_2_0()); }
	'='
	{ after(grammarAccess.getClockAccess().getEqualsSignKeyword_2_0()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__Clock__Group_2__1
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Clock__Group_2__1__Impl
;
finally {
	restoreStackSize(stackSize);
}

rule__Clock__Group_2__1__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getClockAccess().getInitialValueAssignment_2_1()); }
	(rule__Clock__InitialValueAssignment_2_1)
	{ after(grammarAccess.getClockAccess().getInitialValueAssignment_2_1()); }
)
;
finally {
	restoreStackSize(stackSize);
}


rule__CycleDef__Group__0
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__CycleDef__Group__0__Impl
	rule__CycleDef__Group__1
;
finally {
	restoreStackSize(stackSize);
}

rule__CycleDef__Group__0__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getCycleDefAccess().getCycleDefKeyword_0()); }
	'cycleDef'
	{ after(grammarAccess.getCycleDefAccess().getCycleDefKeyword_0()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__CycleDef__Group__1
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__CycleDef__Group__1__Impl
	rule__CycleDef__Group__2
;
finally {
	restoreStackSize(stackSize);
}

rule__CycleDef__Group__1__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getCycleDefAccess().getCycleKeyword_1()); }
	'cycle'
	{ after(grammarAccess.getCycleDefAccess().getCycleKeyword_1()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__CycleDef__Group__2
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__CycleDef__Group__2__Impl
	rule__CycleDef__Group__3
;
finally {
	restoreStackSize(stackSize);
}

rule__CycleDef__Group__2__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getCycleDefAccess().getEqualsSignEqualsSignKeyword_2()); }
	'=='
	{ after(grammarAccess.getCycleDefAccess().getEqualsSignEqualsSignKeyword_2()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__CycleDef__Group__3
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__CycleDef__Group__3__Impl
;
finally {
	restoreStackSize(stackSize);
}

rule__CycleDef__Group__3__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getCycleDefAccess().getValueAssignment_3()); }
	(rule__CycleDef__ValueAssignment_3)
	{ after(grammarAccess.getCycleDefAccess().getValueAssignment_3()); }
)
;
finally {
	restoreStackSize(stackSize);
}


rule__Model__InterfaceAssignment_0
	@init {
		int stackSize = keepStackSize();
	}
:
	(
		{ before(grammarAccess.getModelAccess().getInterfaceInterfaceParserRuleCall_0_0()); }
		ruleInterface
		{ after(grammarAccess.getModelAccess().getInterfaceInterfaceParserRuleCall_0_0()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

rule__Model__NameAssignment_2
	@init {
		int stackSize = keepStackSize();
	}
:
	(
		{ before(grammarAccess.getModelAccess().getNameIDTerminalRuleCall_2_0()); }
		RULE_ID
		{ after(grammarAccess.getModelAccess().getNameIDTerminalRuleCall_2_0()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

rule__Model__CycleDefAssignment_4
	@init {
		int stackSize = keepStackSize();
	}
:
	(
		{ before(grammarAccess.getModelAccess().getCycleDefCycleDefParserRuleCall_4_0()); }
		ruleCycleDef
		{ after(grammarAccess.getModelAccess().getCycleDefCycleDefParserRuleCall_4_0()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

rule__Model__ConstantsAssignment_5
	@init {
		int stackSize = keepStackSize();
	}
:
	(
		{ before(grammarAccess.getModelAccess().getConstantsConstantParserRuleCall_5_0()); }
		ruleConstant
		{ after(grammarAccess.getModelAccess().getConstantsConstantParserRuleCall_5_0()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

rule__Model__VariablesAssignment_6
	@init {
		int stackSize = keepStackSize();
	}
:
	(
		{ before(grammarAccess.getModelAccess().getVariablesVariableParserRuleCall_6_0()); }
		ruleVariable
		{ after(grammarAccess.getModelAccess().getVariablesVariableParserRuleCall_6_0()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

rule__Model__ClockAssignment_7
	@init {
		int stackSize = keepStackSize();
	}
:
	(
		{ before(grammarAccess.getModelAccess().getClockClockParserRuleCall_7_0()); }
		ruleClock
		{ after(grammarAccess.getModelAccess().getClockClockParserRuleCall_7_0()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

rule__Model__ContextsAssignment_8
	@init {
		int stackSize = keepStackSize();
	}
:
	(
		{ before(grammarAccess.getModelAccess().getContextsContextDeclParserRuleCall_8_0()); }
		ruleContextDecl
		{ after(grammarAccess.getModelAccess().getContextsContextDeclParserRuleCall_8_0()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

rule__Interface__NameAssignment_1
	@init {
		int stackSize = keepStackSize();
	}
:
	(
		{ before(grammarAccess.getInterfaceAccess().getNameIDTerminalRuleCall_1_0()); }
		RULE_ID
		{ after(grammarAccess.getInterfaceAccess().getNameIDTerminalRuleCall_1_0()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

rule__Interface__OperationsAssignment_3_0
	@init {
		int stackSize = keepStackSize();
	}
:
	(
		{ before(grammarAccess.getInterfaceAccess().getOperationsOperationDeclParserRuleCall_3_0_0()); }
		ruleOperationDecl
		{ after(grammarAccess.getInterfaceAccess().getOperationsOperationDeclParserRuleCall_3_0_0()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

rule__Interface__EventsAssignment_3_1
	@init {
		int stackSize = keepStackSize();
	}
:
	(
		{ before(grammarAccess.getInterfaceAccess().getEventsEventDeclParserRuleCall_3_1_0()); }
		ruleEventDecl
		{ after(grammarAccess.getInterfaceAccess().getEventsEventDeclParserRuleCall_3_1_0()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

rule__OperationDecl__NameAssignment_0
	@init {
		int stackSize = keepStackSize();
	}
:
	(
		{ before(grammarAccess.getOperationDeclAccess().getNameIDTerminalRuleCall_0_0()); }
		RULE_ID
		{ after(grammarAccess.getOperationDeclAccess().getNameIDTerminalRuleCall_0_0()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

rule__OperationDecl__ParamsAssignment_2_0
	@init {
		int stackSize = keepStackSize();
	}
:
	(
		{ before(grammarAccess.getOperationDeclAccess().getParamsParamParserRuleCall_2_0_0()); }
		ruleParam
		{ after(grammarAccess.getOperationDeclAccess().getParamsParamParserRuleCall_2_0_0()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

rule__OperationDecl__ParamsAssignment_2_1_1
	@init {
		int stackSize = keepStackSize();
	}
:
	(
		{ before(grammarAccess.getOperationDeclAccess().getParamsParamParserRuleCall_2_1_1_0()); }
		ruleParam
		{ after(grammarAccess.getOperationDeclAccess().getParamsParamParserRuleCall_2_1_1_0()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

rule__EventDecl__NameAssignment_1
	@init {
		int stackSize = keepStackSize();
	}
:
	(
		{ before(grammarAccess.getEventDeclAccess().getNameIDTerminalRuleCall_1_0()); }
		RULE_ID
		{ after(grammarAccess.getEventDeclAccess().getNameIDTerminalRuleCall_1_0()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

rule__Param__NameAssignment_0
	@init {
		int stackSize = keepStackSize();
	}
:
	(
		{ before(grammarAccess.getParamAccess().getNameIDTerminalRuleCall_0_0()); }
		RULE_ID
		{ after(grammarAccess.getParamAccess().getNameIDTerminalRuleCall_0_0()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

rule__Param__TypeAssignment_2
	@init {
		int stackSize = keepStackSize();
	}
:
	(
		{ before(grammarAccess.getParamAccess().getTypeDataTypeEnumRuleCall_2_0()); }
		ruleDataType
		{ after(grammarAccess.getParamAccess().getTypeDataTypeEnumRuleCall_2_0()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

rule__ContextDecl__KindAssignment_0
	@init {
		int stackSize = keepStackSize();
	}
:
	(
		{ before(grammarAccess.getContextDeclAccess().getKindAlternatives_0_0()); }
		(rule__ContextDecl__KindAlternatives_0_0)
		{ after(grammarAccess.getContextDeclAccess().getKindAlternatives_0_0()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

rule__ContextDecl__UsedInterfacesAssignment_4
	@init {
		int stackSize = keepStackSize();
	}
:
	(
		{ before(grammarAccess.getContextDeclAccess().getUsedInterfacesInterfaceCrossReference_4_0()); }
		(
			{ before(grammarAccess.getContextDeclAccess().getUsedInterfacesInterfaceIDTerminalRuleCall_4_0_1()); }
			RULE_ID
			{ after(grammarAccess.getContextDeclAccess().getUsedInterfacesInterfaceIDTerminalRuleCall_4_0_1()); }
		)
		{ after(grammarAccess.getContextDeclAccess().getUsedInterfacesInterfaceCrossReference_4_0()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

rule__ContextDecl__UsedInterfacesAssignment_5_1
	@init {
		int stackSize = keepStackSize();
	}
:
	(
		{ before(grammarAccess.getContextDeclAccess().getUsedInterfacesInterfaceCrossReference_5_1_0()); }
		(
			{ before(grammarAccess.getContextDeclAccess().getUsedInterfacesInterfaceIDTerminalRuleCall_5_1_0_1()); }
			RULE_ID
			{ after(grammarAccess.getContextDeclAccess().getUsedInterfacesInterfaceIDTerminalRuleCall_5_1_0_1()); }
		)
		{ after(grammarAccess.getContextDeclAccess().getUsedInterfacesInterfaceCrossReference_5_1_0()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

rule__ContextDecl__OpsAssignment_6_0
	@init {
		int stackSize = keepStackSize();
	}
:
	(
		{ before(grammarAccess.getContextDeclAccess().getOpsOperationDeclParserRuleCall_6_0_0()); }
		ruleOperationDecl
		{ after(grammarAccess.getContextDeclAccess().getOpsOperationDeclParserRuleCall_6_0_0()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

rule__ContextDecl__EventsAssignment_6_1
	@init {
		int stackSize = keepStackSize();
	}
:
	(
		{ before(grammarAccess.getContextDeclAccess().getEventsEventDeclParserRuleCall_6_1_0()); }
		ruleEventDecl
		{ after(grammarAccess.getContextDeclAccess().getEventsEventDeclParserRuleCall_6_1_0()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

rule__Constant__NameAssignment_1
	@init {
		int stackSize = keepStackSize();
	}
:
	(
		{ before(grammarAccess.getConstantAccess().getNameIDTerminalRuleCall_1_0()); }
		RULE_ID
		{ after(grammarAccess.getConstantAccess().getNameIDTerminalRuleCall_1_0()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

rule__Constant__TypeAssignment_3
	@init {
		int stackSize = keepStackSize();
	}
:
	(
		{ before(grammarAccess.getConstantAccess().getTypeDataTypeEnumRuleCall_3_0()); }
		ruleDataType
		{ after(grammarAccess.getConstantAccess().getTypeDataTypeEnumRuleCall_3_0()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

rule__Variable__NameAssignment_1
	@init {
		int stackSize = keepStackSize();
	}
:
	(
		{ before(grammarAccess.getVariableAccess().getNameIDTerminalRuleCall_1_0()); }
		RULE_ID
		{ after(grammarAccess.getVariableAccess().getNameIDTerminalRuleCall_1_0()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

rule__Variable__TypeAssignment_3
	@init {
		int stackSize = keepStackSize();
	}
:
	(
		{ before(grammarAccess.getVariableAccess().getTypeDataTypeEnumRuleCall_3_0()); }
		ruleDataType
		{ after(grammarAccess.getVariableAccess().getTypeDataTypeEnumRuleCall_3_0()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

rule__Variable__InitialValueAssignment_4_1
	@init {
		int stackSize = keepStackSize();
	}
:
	(
		{ before(grammarAccess.getVariableAccess().getInitialValueINTTerminalRuleCall_4_1_0()); }
		RULE_INT
		{ after(grammarAccess.getVariableAccess().getInitialValueINTTerminalRuleCall_4_1_0()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

rule__Clock__NameAssignment_1
	@init {
		int stackSize = keepStackSize();
	}
:
	(
		{ before(grammarAccess.getClockAccess().getNameIDTerminalRuleCall_1_0()); }
		RULE_ID
		{ after(grammarAccess.getClockAccess().getNameIDTerminalRuleCall_1_0()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

rule__Clock__InitialValueAssignment_2_1
	@init {
		int stackSize = keepStackSize();
	}
:
	(
		{ before(grammarAccess.getClockAccess().getInitialValueINTTerminalRuleCall_2_1_0()); }
		RULE_INT
		{ after(grammarAccess.getClockAccess().getInitialValueINTTerminalRuleCall_2_1_0()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

rule__CycleDef__ValueAssignment_3
	@init {
		int stackSize = keepStackSize();
	}
:
	(
		{ before(grammarAccess.getCycleDefAccess().getValueINTTerminalRuleCall_3_0()); }
		RULE_INT
		{ after(grammarAccess.getCycleDefAccess().getValueINTTerminalRuleCall_3_0()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

RULE_ID : '^'? ('a'..'z'|'A'..'Z'|'_') ('a'..'z'|'A'..'Z'|'_'|'0'..'9')*;

RULE_INT : ('0'..'9')+;

RULE_STRING : ('"' ('\\' .|~(('\\'|'"')))* '"'|'\'' ('\\' .|~(('\\'|'\'')))* '\'');

RULE_ML_COMMENT : '/*' ( options {greedy=false;} : . )*'*/';

RULE_SL_COMMENT : '//' ~(('\n'|'\r'))* ('\r'? '\n')?;

RULE_WS : (' '|'\t'|'\r'|'\n')+;

RULE_ANY_OTHER : .;
